package shim

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"

	"github.com/safedep/dry/log"
	"github.com/safedep/pmg/internal/fsutil"
)

const (
	// pmgBinSuffix matches the legacy per-user shim dir (~/.pmg/bin). Retained
	// as a fallback so shims installed by older PMG versions keep working after
	// upgrade, until they are regenerated by a fresh `pmg setup install`.
	pmgBinSuffix = "/.pmg/bin"

	// pmgDataBinSuffix matches the per-user shim dir under the data directory
	// (<data dir>/bin, e.g. ~/.local/share/safedep/pmg/bin). Matched by suffix
	// rather than resolved, so an aliased invocation strips it without a
	// filesystem lookup and regardless of where XDG_DATA_HOME points.
	pmgDataBinSuffix = "/safedep/pmg/bin"

	// pmgShimPathEnv is the env var the shim script exports before exec'ing
	// pmg. Its value is the absolute path of the shim that was invoked, which
	// lets FilterPMGFromPath strip exactly the dir the shim lives in — no
	// matter where it was placed (`~/.pmg/bin`, `/usr/local/lib/pmg/bin`, a
	// custom location, etc.).
	//
	// Internal: set by the shim script, consumed by pmg in the same process
	// tree. Setting it manually from a user shell is unsupported — it would
	// cause FilterPMGFromPath to strip the wrong directory from PATH lookup
	// and could prevent pmg from resolving the real package manager.
	pmgShimPathEnv = "PMG_SHIM_PATH"
)

var resolverMu sync.Mutex

func FilterPMGFromPath(pathEnv string) string {
	if pathEnv == "" {
		return ""
	}

	shimDirs := append([]string{SystemBinDir()}, userBinDirs()...)
	if shimPath := os.Getenv(pmgShimPathEnv); shimPath != "" {
		shimDirs = append(shimDirs, filepath.Dir(shimPath))
	}

	entries := filepath.SplitList(pathEnv)
	filtered := make([]string, 0, len(entries))

	for _, entry := range entries {
		if !isShimDir(entry, shimDirs) {
			filtered = append(filtered, entry)
		}
	}

	return strings.Join(filtered, string(os.PathListSeparator))
}

func isShimDir(entry string, shimDirs []string) bool {
	if strings.HasSuffix(entry, pmgBinSuffix) || strings.HasSuffix(entry, pmgDataBinSuffix) {
		return true
	}
	for _, dir := range shimDirs {
		if fsutil.SamePath(entry, dir) {
			return true
		}
	}
	return false
}

// userBinDirs lists both per-user shim directories. The suffix constants
// above are written with forward slashes and never match a Windows path, and
// doctor and a direct `pmg npm` run without PMG_SHIM_PATH. Without this
// comparison ResolveRealBinary finds PMG's own shim on Windows and PMG
// re-enters itself.
func userBinDirs() []string {
	var dirs []string
	if dir, err := LegacyUserBinDir(); err == nil {
		dirs = append(dirs, dir)
	}
	if dir, err := DataUserBinDir(); err == nil {
		dirs = append(dirs, dir)
	}
	return dirs
}

// ResolveRealBinary finds the real binary path for a command by searching
// PATH with the pmg shim directories stripped out. This prevents exec.CommandContext from
// resolving to the shim script, which would cause infinite recursion.
func ResolveRealBinary(name string) (string, error) {
	resolverMu.Lock()
	defer resolverMu.Unlock()

	originalPath := os.Getenv("PATH")
	filteredPath := FilterPMGFromPath(originalPath)

	if err := os.Setenv("PATH", filteredPath); err != nil {
		return "", fmt.Errorf("failed to set filtered PATH: %w", err)
	}
	defer func() {
		if err := os.Setenv("PATH", originalPath); err != nil {
			log.Warnf("failed to restore PATH: %v", err)
		}
	}()

	resolved, err := exec.LookPath(name)
	if err != nil {
		if errors.Is(err, exec.ErrNotFound) {
			return "", &BinaryNotFoundError{Name: name}
		}
		return "", fmt.Errorf("could not find %s in PATH (excluding pmg shims): %w", name, err)
	}

	return resolved, nil
}

func FilterPMGFromEnv(env []string) []string {
	result := make([]string, 0, len(env))

	// Windows os.Environ() returns `Path=`, so the key match folds case. A
	// prefix match kept the shim directory on the child PATH, and an npm
	// lifecycle script that called npm re-entered the shim and PMG.
	for _, entry := range env {
		key, value, ok := strings.Cut(entry, "=")
		if ok && strings.EqualFold(key, "PATH") {
			result = append(result, key+"="+FilterPMGFromPath(value))
			continue
		}
		// Drop PMG_SHIM_PATH so child processes don't inherit a stale marker
		// from the shim invocation that triggered this exec.
		if ok && strings.EqualFold(key, pmgShimPathEnv) {
			continue
		}
		result = append(result, entry)
	}

	return result
}
