// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm) && linux

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type EnforceCfg struct {
	_           structs.HostLayout
	ProxyIp4    uint32
	ProxyPort   uint16
	Flags       uint16
	DaemonTgid  uint32
	Pad         uint32
	NetnsCookie uint64
	ProxyIp6    [4]uint32
}

type EnforceDst struct {
	_      structs.HostLayout
	Family uint16
	Port   uint16
	Addr   [16]uint8
}

type EnforceDstKey struct {
	_      structs.HostLayout
	Family uint16
	Sport  uint16
}

type EnforceEvent struct {
	_      structs.HostLayout
	Tgid   uint32
	Uid    uint32
	Family uint16
	Dport  uint16
	Action uint8
	Proto  uint8
	Pad    [2]uint8
	Dst    [16]uint8
	ExeDev uint64
	ExeIno uint64
	Comm   [16]int8
}

type EnforceExeKey struct {
	_   structs.HostLayout
	Dev uint64
	Ino uint64
}

type EnforceExecEvent struct {
	_    structs.HostLayout
	Dev  uint64
	Ino  uint64
	Tgid uint32
	Pad  uint32
}

type EnforceSkip4Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type EnforceSkip6Key struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	EnforceMapEligibleUid     = "eligible_uid"
	EnforceMapEvents          = "events"
	EnforceMapExecEvents      = "exec_events"
	EnforceMapExemptExe       = "exempt_exe"
	EnforceMapExemptUid       = "exempt_uid"
	EnforceMapOrigDst         = "orig_dst"
	EnforceMapOrigDstSk       = "orig_dst_sk"
	EnforceMapPmgCfg          = "pmg_cfg"
	EnforceMapPorts           = "ports"
	EnforceMapSeenExe         = "seen_exe"
	EnforceMapSkip4           = "skip4"
	EnforceMapSkip6           = "skip6"
	EnforceMapStats           = "stats"
	EnforceProgPmgConnect4    = "pmg_connect4"
	EnforceProgPmgConnect6    = "pmg_connect6"
	EnforceProgPmgExec        = "pmg_exec"
	EnforceProgPmgSendmsg4    = "pmg_sendmsg4"
	EnforceProgPmgSendmsg6    = "pmg_sendmsg6"
	EnforceProgPmgSockops     = "pmg_sockops"
	EnforceVarUnusedEvent     = "unused_event"
	EnforceVarUnusedExecEvent = "unused_exec_event"
)

// LoadEnforce returns the embedded CollectionSpec for Enforce.
func LoadEnforce() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EnforceBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Enforce: %w", err)
	}

	return spec, err
}

// LoadEnforceObjects loads Enforce and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*EnforceObjects
//	*EnforcePrograms
//	*EnforceMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadEnforceObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadEnforce()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// EnforceSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EnforceSpecs struct {
	EnforceProgramSpecs
	EnforceMapSpecs
	EnforceVariableSpecs
}

// EnforceProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EnforceProgramSpecs struct {
	PmgConnect4 *ebpf.ProgramSpec `ebpf:"pmg_connect4"`
	PmgConnect6 *ebpf.ProgramSpec `ebpf:"pmg_connect6"`
	PmgExec     *ebpf.ProgramSpec `ebpf:"pmg_exec"`
	PmgSendmsg4 *ebpf.ProgramSpec `ebpf:"pmg_sendmsg4"`
	PmgSendmsg6 *ebpf.ProgramSpec `ebpf:"pmg_sendmsg6"`
	PmgSockops  *ebpf.ProgramSpec `ebpf:"pmg_sockops"`
}

// EnforceMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EnforceMapSpecs struct {
	EligibleUid *ebpf.MapSpec `ebpf:"eligible_uid"`
	Events      *ebpf.MapSpec `ebpf:"events"`
	ExecEvents  *ebpf.MapSpec `ebpf:"exec_events"`
	ExemptExe   *ebpf.MapSpec `ebpf:"exempt_exe"`
	ExemptUid   *ebpf.MapSpec `ebpf:"exempt_uid"`
	OrigDst     *ebpf.MapSpec `ebpf:"orig_dst"`
	OrigDstSk   *ebpf.MapSpec `ebpf:"orig_dst_sk"`
	PmgCfg      *ebpf.MapSpec `ebpf:"pmg_cfg"`
	Ports       *ebpf.MapSpec `ebpf:"ports"`
	SeenExe     *ebpf.MapSpec `ebpf:"seen_exe"`
	Skip4       *ebpf.MapSpec `ebpf:"skip4"`
	Skip6       *ebpf.MapSpec `ebpf:"skip6"`
	Stats       *ebpf.MapSpec `ebpf:"stats"`
}

// EnforceVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EnforceVariableSpecs struct {
	UnusedEvent     *ebpf.VariableSpec `ebpf:"unused_event"`
	UnusedExecEvent *ebpf.VariableSpec `ebpf:"unused_exec_event"`
}

// EnforceObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadEnforceObjects or ebpf.CollectionSpec.LoadAndAssign.
type EnforceObjects struct {
	EnforcePrograms
	EnforceMaps
	EnforceVariables
}

func (o *EnforceObjects) Close() error {
	return _EnforceClose(
		&o.EnforcePrograms,
		&o.EnforceMaps,
	)
}

// EnforceMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadEnforceObjects or ebpf.CollectionSpec.LoadAndAssign.
type EnforceMaps struct {
	EligibleUid *ebpf.Map `ebpf:"eligible_uid"`
	Events      *ebpf.Map `ebpf:"events"`
	ExecEvents  *ebpf.Map `ebpf:"exec_events"`
	ExemptExe   *ebpf.Map `ebpf:"exempt_exe"`
	ExemptUid   *ebpf.Map `ebpf:"exempt_uid"`
	OrigDst     *ebpf.Map `ebpf:"orig_dst"`
	OrigDstSk   *ebpf.Map `ebpf:"orig_dst_sk"`
	PmgCfg      *ebpf.Map `ebpf:"pmg_cfg"`
	Ports       *ebpf.Map `ebpf:"ports"`
	SeenExe     *ebpf.Map `ebpf:"seen_exe"`
	Skip4       *ebpf.Map `ebpf:"skip4"`
	Skip6       *ebpf.Map `ebpf:"skip6"`
	Stats       *ebpf.Map `ebpf:"stats"`
}

func (m *EnforceMaps) Close() error {
	return _EnforceClose(
		m.EligibleUid,
		m.Events,
		m.ExecEvents,
		m.ExemptExe,
		m.ExemptUid,
		m.OrigDst,
		m.OrigDstSk,
		m.PmgCfg,
		m.Ports,
		m.SeenExe,
		m.Skip4,
		m.Skip6,
		m.Stats,
	)
}

// EnforceVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadEnforceObjects or ebpf.CollectionSpec.LoadAndAssign.
type EnforceVariables struct {
	UnusedEvent     *ebpf.Variable `ebpf:"unused_event"`
	UnusedExecEvent *ebpf.Variable `ebpf:"unused_exec_event"`
}

// EnforcePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadEnforceObjects or ebpf.CollectionSpec.LoadAndAssign.
type EnforcePrograms struct {
	PmgConnect4 *ebpf.Program `ebpf:"pmg_connect4"`
	PmgConnect6 *ebpf.Program `ebpf:"pmg_connect6"`
	PmgExec     *ebpf.Program `ebpf:"pmg_exec"`
	PmgSendmsg4 *ebpf.Program `ebpf:"pmg_sendmsg4"`
	PmgSendmsg6 *ebpf.Program `ebpf:"pmg_sendmsg6"`
	PmgSockops  *ebpf.Program `ebpf:"pmg_sockops"`
}

func (p *EnforcePrograms) Close() error {
	return _EnforceClose(
		p.PmgConnect4,
		p.PmgConnect6,
		p.PmgExec,
		p.PmgSendmsg4,
		p.PmgSendmsg6,
		p.PmgSockops,
	)
}

func _EnforceClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed enforce_bpfel.o
var _EnforceBytes []byte
