#!/bin/bash
# Code generated by generate_standalone_linux.sh. Do not edit directly.
# lib_linux.sh — shared helpers for the PMG Linux install/uninstall scripts.
#
# MDM tools (JumpCloud, Intune for Linux, ...) run scripts either as root or
# already as the logged-in user. These helpers make both work without the
# caller branching on it:
#
#   - Machine-scope actions (the pmg binary, /etc config) go through
#     run_as_root.
#   - Per-user actions (config, aliases, shims, Secret Service credentials)
#     go through the user-scope helpers, which fan out to every local user
#     when run as root and act on the current user when run as that user.
#
# Secret Service access needs the user's D-Bus session, so credential steps
# are gated on user_has_session and dispatched with the session bus address
# set. Linux has no Homebrew path; the binary always comes from the GitHub
# release tarball.
#
# This file is sourced by the install/uninstall scripts; deploy them together.

require_linux() {
  if [[ "$(uname -s)" != "Linux" ]]; then
    echo "Error: this script is for Linux only" >&2
    exit 1
  fi
}

log() { echo "==> $*"; }
warn() { echo "==> warning: $*" >&2; }

running_as_root() { [[ "$EUID" -eq 0 ]]; }

# Run a machine-scope command, elevating only if we are not already root.
run_as_root() {
  if running_as_root; then "$@"; else sudo "$@"; fi
}

# Emit "user<TAB>uid<TAB>home" per target user.
#   - as root: every local human account (UID >= UID_MIN from login.defs,
#     default 1000) with a real home under /home.
#   - as a user: just the current user (the MDM ran us in user context).
each_target_user() {
  if ! running_as_root; then
    printf '%s\t%s\t%s\n' "$(id -un)" "$(id -u)" "$HOME"
    return
  fi
  local uid_min
  uid_min=$(awk '/^UID_MIN/{print $2}' /etc/login.defs 2>/dev/null)
  [[ "$uid_min" =~ ^[0-9]+$ ]] || uid_min=1000
  local user uid home
  while IFS=: read -r user _ uid _ _ home _; do
    [[ "$uid" -ge "$uid_min" ]] || continue
    [[ -n "$home" && -d "$home" ]] || continue
    case "$home" in /home/*) ;; *) continue ;; esac
    printf '%s\t%s\t%s\n' "$user" "$uid" "$home"
  done < <(getent passwd)
}

# True if this user has a reachable D-Bus session bus (a live login session).
user_has_session() {
  local uid
  if running_as_root; then
    uid=$(id -u "$1")
  else
    [[ "$1" == "$(id -un)" ]] || return 1
    uid=$(id -u)
  fi
  [[ -S "/run/user/${uid}/bus" ]]
}

# Run a file-scope command as the given user, with HOME set to their home.
run_user_file() {
  local user="$1"; shift
  if running_as_root; then sudo -u "$user" -H -- "$@"; else "$@"; fi
}

# Run a session-scope command (e.g. Secret Service) with the user's D-Bus
# session bus address set. Only call when user_has_session "$user" is true.
run_user_session() {
  local user="$1"; shift
  local uid
  if running_as_root; then
    uid=$(id -u "$user")
    sudo -u "$user" -H -- \
      env "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/${uid}/bus" "$@"
  else
    "$@"
  fi
}

# Per-user pmg state directories: env overrides win, else the XDG layout.
pmg_config_dir() { echo "${PMG_CONFIG_DIR:-$1/.config/safedep/pmg}"; }
pmg_cache_dir() { echo "${PMG_CACHE_DIR:-$1/.cache/safedep/pmg}"; }

# Absolute path to the pmg binary. root's PATH under an MDM is often minimal,
# so fall back to the machine-wide install location.
resolve_pmg() {
  local p
  p=$(command -v pmg 2>/dev/null) && { echo "$p"; return 0; }
  [[ -x /usr/local/bin/pmg ]] && { echo /usr/local/bin/pmg; return 0; }
  return 1
}

# Machine-wide globally managed config. When this file is present pmg treats
# it as authoritative and ignores every user's config. It must match the path
# pmg resolves on Linux.
readonly GLOBAL_CONFIG_DIR="/etc/safedep/pmg"
readonly GLOBAL_CONFIG_FILE="${GLOBAL_CONFIG_DIR}/config.yml"

# install_global_config <src> installs a bundled config.yml as the globally
# managed config: root-owned and 0644 so users can read but not modify it.
install_global_config() {
  local src="$1"
  log "Installing globally managed config to $GLOBAL_CONFIG_FILE"
  run_as_root install -d -m 0755 "$GLOBAL_CONFIG_DIR" || { warn "failed to create $GLOBAL_CONFIG_DIR (need root)"; return 1; }
  run_as_root install -m 0644 "$src" "$GLOBAL_CONFIG_FILE" || { warn "failed to install global config (need root)"; return 1; }
}

# remove_global_config removes the globally managed config when present,
# unless PMG_KEEP_GLOBAL_CONFIG is set.
remove_global_config() {
  if [[ -n "${PMG_KEEP_GLOBAL_CONFIG:-}" ]]; then
    [[ -e "$GLOBAL_CONFIG_FILE" ]] && log "Keeping globally managed config ($GLOBAL_CONFIG_FILE); PMG_KEEP_GLOBAL_CONFIG is set"
    return 0
  fi

  [[ -e "$GLOBAL_CONFIG_FILE" ]] || return 0
  log "Removing globally managed config $GLOBAL_CONFIG_FILE"
  run_as_root rm -f "$GLOBAL_CONFIG_FILE" || warn "failed to remove global config (need root)"
  run_as_root rmdir "$GLOBAL_CONFIG_DIR" 2>/dev/null || true
}
# pmg_uninstall_linux.sh — Remove PMG from a Linux machine.
#
# Deploy via JumpCloud or any MDM, alongside lib_linux.sh in the same
# directory. Run as root, it cleans up every local user's config, aliases,
# shims, and (for users with an active session) keyring credentials, then
# removes the machine-wide binary. Run as a user, it cleans up just that
# user. See lib_linux.sh for the model.

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
: "$SCRIPT_DIR"

require_linux

PMG_BIN=$(resolve_pmg || true)

remove_user_state() {
  local user="$1" home="$2"
  log "Removing pmg state for $user"

  if [[ -n "$PMG_BIN" ]]; then
    run_user_file "$user" "$PMG_BIN" setup remove \
      || warn "failed to remove aliases/shims for $user"
  else
    warn "pmg binary not found; shell rc entries for $user may remain"
  fi

  run_user_file "$user" rm -rf \
    "$(pmg_config_dir "$home")" "$(pmg_cache_dir "$home")" \
    "$home/.pmg" "$home/.pmg.rc" "$home/.local/bin/pmg" \
    || warn "failed to remove pmg directories for $user"

  if [[ -z "$PMG_BIN" ]]; then
    return
  fi
  if user_has_session "$user"; then
    run_user_session "$user" "$PMG_BIN" cloud logout \
      || warn "failed to clear keyring credentials for $user"
  else
    log "  $user has no active session; keyring credentials (if any) will clear on next login"
  fi
}

while IFS=$'\t' read -r user _ home; do
  remove_user_state "$user" "$home"
done < <(each_target_user)

remove_binary() {
  if [[ -e /usr/local/bin/pmg ]]; then
    log "Removing /usr/local/bin/pmg"
    run_as_root rm -f /usr/local/bin/pmg || warn "failed to remove /usr/local/bin/pmg (need root)"
  fi
}
remove_binary

remove_global_config

log "pmg uninstall complete"
