#!/bin/bash
# Code generated by generate_standalone_scripts.sh. Do not edit directly.
# lib_macos.sh — shared helpers for the PMG macOS install/uninstall scripts.
#
# MDM tools (Jamf, Mosyle, Kandji, Intune, ...) run scripts either as root or
# already as the logged-in user. These helpers make both work without the caller
# branching on it:
#
#   - Machine-scope actions (the pmg binary) go through run_as_root.
#   - Per-user actions (config, aliases, shims, Keychain) go through the
#     user-scope helpers, which fan out to every local user when run as root and
#     act on the current user when run as that user.
#
# Keychain access needs the user's GUI session, so credential steps are gated on
# user_has_session and dispatched via `launchctl asuser`. Homebrew refuses to run
# as root, so brew steps run as the owner of the Homebrew install via run_brew.
#
# This file is sourced by the install/uninstall scripts; deploy them together.

require_macos() {
  if [[ "$(uname -s)" != "Darwin" ]]; then
    echo "Error: this script is for macOS only" >&2
    exit 1
  fi
}

log() { echo "==> $*"; }
warn() { echo "==> warning: $*" >&2; }

running_as_root() { [[ "$EUID" -eq 0 ]]; }

# Path to a Homebrew binary (Apple Silicon or Intel), or non-zero if absent.
find_brew() {
  local candidate
  for candidate in /opt/homebrew/bin/brew /usr/local/bin/brew; do
    [[ -x "$candidate" ]] && { echo "$candidate"; return 0; }
  done
  return 1
}

# Run a machine-scope command, elevating only if we are not already root.
run_as_root() {
  if running_as_root; then "$@"; else sudo "$@"; fi
}

# brew refuses to run as root, so run it as the owner of the Homebrew install.
run_brew() {
  local brew_bin="$1"; shift
  local owner; owner=$(stat -f%Su "$brew_bin")
  if [[ "$owner" == "$(id -un)" ]]; then
    "$brew_bin" "$@"
  elif running_as_root && [[ "$owner" != "root" ]]; then
    sudo -u "$owner" -H -- "$brew_bin" "$@"
  else
    warn "cannot run brew as $(id -un); Homebrew is owned by $owner"
    return 1
  fi
}

# The console (GUI logged-in) user, or non-zero if none / at the login window.
console_user() {
  local u
  u=$(stat -f%Su /dev/console 2>/dev/null || true)
  [[ -z "$u" || "$u" == "root" || "$u" == "loginwindow" ]] && return 1
  echo "$u"
}

# Emit "user<TAB>uid<TAB>home" per target user.
#   - as root: every local human account (UID >= 500) with a real home.
#   - as a user: just the current user (the MDM ran us in user context).
each_target_user() {
  if ! running_as_root; then
    printf '%s\t%s\t%s\n' "$(id -un)" "$(id -u)" "$HOME"
    return
  fi
  local user uid home
  while IFS= read -r user; do
    uid=$(dscl . -read "/Users/$user" UniqueID 2>/dev/null | awk '{print $2}')
    if ! [[ "$uid" =~ ^[0-9]+$ ]] || [[ "$uid" -lt 500 ]]; then continue; fi
    home=$(dscl . -read "/Users/$user" NFSHomeDirectory 2>/dev/null | awk '{print $2}')
    [[ -n "$home" && -d "$home" ]] || continue
    case "$home" in /Users/*) ;; *) continue ;; esac
    printf '%s\t%s\t%s\n' "$user" "$uid" "$home"
  done < <(dscl . -list /Users)
}

# True if this user's login Keychain is reachable (they have a live session).
user_has_session() {
  if running_as_root; then
    [[ "$1" == "$(console_user || true)" ]]
  else
    [[ "$1" == "$(id -un)" ]]
  fi
}

# Run a file-scope command as the given user, with HOME set to their home.
run_user_file() {
  local user="$1"; shift
  if running_as_root; then sudo -u "$user" -H -- "$@"; else "$@"; fi
}

# Run a session-scope command (e.g. Keychain) inside the user's GUI session.
# Only call when user_has_session "$user" is true.
run_user_session() {
  local user="$1"; shift
  if running_as_root; then
    launchctl asuser "$(id -u "$user")" sudo -u "$user" -H -- "$@"
  else
    "$@"
  fi
}

# Per-user pmg state directories: env overrides win, else the macOS layout.
pmg_config_dir() { echo "${PMG_CONFIG_DIR:-$1/Library/Application Support/safedep/pmg}"; }
pmg_cache_dir() { echo "${PMG_CACHE_DIR:-$1/Library/Caches/safedep/pmg}"; }

# Absolute path to the pmg binary. root's PATH under an MDM is often minimal, so
# fall back to the machine-wide install locations.
resolve_pmg() {
  local p
  p=$(command -v pmg 2>/dev/null) && { echo "$p"; return 0; }
  for p in /usr/local/bin/pmg /opt/homebrew/bin/pmg; do
    [[ -x "$p" ]] && { echo "$p"; return 0; }
  done
  return 1
}

# Machine-wide globally managed config. When this file is present pmg treats it as
# authoritative and ignores every user's config. It must match the path pmg
# resolves on macOS.
readonly GLOBAL_CONFIG_DIR="/Library/Application Support/safedep/pmg"
readonly GLOBAL_CONFIG_FILE="${GLOBAL_CONFIG_DIR}/config.yml"

# install_global_config <src> installs a bundled config.yml as the globally
# managed config: root-owned and 0644 so users can read but not modify it.
install_global_config() {
  local src="$1"
  log "Installing globally managed config to $GLOBAL_CONFIG_FILE"
  run_as_root install -d -m 0755 "$GLOBAL_CONFIG_DIR" || { warn "failed to create $GLOBAL_CONFIG_DIR (need root)"; return 1; }
  run_as_root install -m 0644 "$src" "$GLOBAL_CONFIG_FILE" || { warn "failed to install global config (need root)"; return 1; }
}

# remove_global_config removes the globally managed config when present, unless
# PMG_KEEP_GLOBAL_CONFIG is set.
remove_global_config() {
  if [[ -n "${PMG_KEEP_GLOBAL_CONFIG:-}" ]]; then
    [[ -e "$GLOBAL_CONFIG_FILE" ]] && log "Keeping globally managed config ($GLOBAL_CONFIG_FILE); PMG_KEEP_GLOBAL_CONFIG is set"
    return 0
  fi

  [[ -e "$GLOBAL_CONFIG_FILE" ]] || return 0
  log "Removing globally managed config $GLOBAL_CONFIG_FILE"
  run_as_root rm -f "$GLOBAL_CONFIG_FILE" || warn "failed to remove global config (need root)"
  run_as_root rmdir "$GLOBAL_CONFIG_DIR" 2>/dev/null || true
}
# pmg_setup_install_macos.sh — Install and configure PMG on a Mac.
#
# Deploy via Jamf or any MDM, alongside lib_macos.sh in the same directory.
# Run as root, it installs the machine-wide binary and configures every local
# user (config, aliases, shims). Cloud credentials are stored in the logged-in
# user's Keychain when SAFEDEP_API_KEY and SAFEDEP_TENANT_ID are set. Run as a
# user, it configures just that user. See lib_macos.sh for the model.
#
# Environment variables:
#   SAFEDEP_API_KEY    — SafeDep Cloud API key (with tenant ID, enables cloud sync)
#   SAFEDEP_TENANT_ID  — SafeDep Cloud tenant ID

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

require_macos

REPO="safedep/pmg"
CLOUD_API_KEY="${SAFEDEP_API_KEY:-}"
CLOUD_TENANT_ID="${SAFEDEP_TENANT_ID:-}"

install_via_brew() {
  local brew_bin="$1"
  log "Installing/updating pmg via Homebrew"
  if run_brew "$brew_bin" ls --cask --versions safedep/tap/pmg &>/dev/null; then
    run_brew "$brew_bin" upgrade --cask safedep/tap/pmg || true
  else
    run_brew "$brew_bin" install --cask safedep/tap/pmg
  fi
}

install_via_release() {
  log "Homebrew not found, installing pmg from GitHub releases"
  local install_dir="/usr/local/bin" tag asset url checksums_url tmpdir expected actual

  tag=$(curl -fsSI -o /dev/null -w '%{redirect_url}' "https://github.com/${REPO}/releases/latest" | sed 's|.*/||')
  [[ -n "$tag" ]] || { echo "Error: could not determine latest release" >&2; exit 1; }
  log "Latest release: $tag"

  asset="pmg_Darwin_all.tar.gz"
  url="https://github.com/${REPO}/releases/download/${tag}/${asset}"
  checksums_url="https://github.com/${REPO}/releases/download/${tag}/checksums.txt"

  tmpdir=$(mktemp -d)
  trap 'rm -rf "$tmpdir"' EXIT

  log "Downloading $asset"
  curl -fsSL -o "${tmpdir}/${asset}" "$url"
  curl -fsSL -o "${tmpdir}/checksums.txt" "$checksums_url"

  expected=$(grep "  ${asset}$" "${tmpdir}/checksums.txt" | cut -d' ' -f1)
  [[ -n "$expected" ]] || { echo "Error: no checksum entry found for ${asset}" >&2; exit 1; }
  actual=$(shasum -a 256 "${tmpdir}/${asset}" | cut -d' ' -f1)
  if [[ "$actual" != "$expected" ]]; then
    echo "Error: checksum mismatch for ${asset} (expected $expected, got $actual)" >&2
    exit 1
  fi
  log "Checksum verified"

  tar -xzf "${tmpdir}/${asset}" -C "${tmpdir}" pmg
  run_as_root install -m 755 "${tmpdir}/pmg" "${install_dir}/pmg"
  log "Installed pmg $tag to ${install_dir}/pmg"
}

if brew_bin=$(find_brew); then
  install_via_brew "$brew_bin"
else
  install_via_release
fi

PMG_BIN=$(resolve_pmg) || { echo "Error: pmg not found after install" >&2; exit 1; }
log "pmg installed: $("$PMG_BIN" version 2>/dev/null || echo unknown)"

# Install the globally managed config if the package ships one. Done before the
# per-user loop so each user's `setup install` sees managed mode and skips
# writing a per-user config.
if [[ -f "${SCRIPT_DIR}/config.yml" ]]; then
  install_global_config "${SCRIPT_DIR}/config.yml"
fi

if [[ -f "$GLOBAL_CONFIG_FILE" && -n "$CLOUD_API_KEY" && -n "$CLOUD_TENANT_ID" ]]; then
  log "Config is globally managed; set 'cloud.enabled: true' in the bundled config.yml to enable sync (per-user config is locked)"
fi

configure_user() {
  local user="$1"
  log "Configuring pmg for $user"
  run_user_file "$user" "$PMG_BIN" setup install || { warn "setup failed for $user"; return; }

  [[ -n "$CLOUD_API_KEY" && -n "$CLOUD_TENANT_ID" ]] || return 0
  if ! user_has_session "$user"; then
    log "  $user is not logged in; run 'pmg cloud login' in their session to enable cloud sync"
    return
  fi
  # When config is globally managed, `cloud.enabled` comes from the global file;
  # per-user `config set` is refused. Per-user credentials still go to the Keychain.
  if [[ ! -f "$GLOBAL_CONFIG_FILE" ]]; then
    run_user_file "$user" "$PMG_BIN" config set cloud.enabled true || warn "could not enable cloud sync for $user"
  fi
  run_user_session "$user" \
    env SAFEDEP_API_KEY="$CLOUD_API_KEY" SAFEDEP_TENANT_ID="$CLOUD_TENANT_ID" "$PMG_BIN" cloud login --from-env \
    || warn "cloud login failed for $user"
}

while IFS=$'\t' read -r user _ _; do
  configure_user "$user"
done < <(each_target_user)

log "pmg setup complete"
