#!/bin/bash
# Code generated by generate_standalone_linux.sh. Do not edit directly.
# lib_linux.sh — shared helpers for the PMG Linux install/uninstall scripts.
#
# MDM tools (JumpCloud, Intune for Linux, ...) run scripts either as root or
# already as the logged-in user. These helpers make both work without the
# caller branching on it:
#
#   - Machine-scope actions (the pmg binary, /etc config) go through
#     run_as_root.
#   - Per-user actions (config, aliases, shims, Secret Service credentials)
#     go through the user-scope helpers, which fan out to every local user
#     when run as root and act on the current user when run as that user.
#
# Secret Service access needs the user's D-Bus session, so credential steps
# are gated on user_has_session and dispatched with the session bus address
# set. Linux has no Homebrew path; the binary always comes from the GitHub
# release tarball.
#
# This file is sourced by the install/uninstall scripts; deploy them together.

require_linux() {
  if [[ "$(uname -s)" != "Linux" ]]; then
    echo "Error: this script is for Linux only" >&2
    exit 1
  fi
}

log() { echo "==> $*"; }
warn() { echo "==> warning: $*" >&2; }

running_as_root() { [[ "$EUID" -eq 0 ]]; }

# Run a machine-scope command, elevating only if we are not already root.
run_as_root() {
  if running_as_root; then "$@"; else sudo -n "$@"; fi
}

# Emit "user<TAB>uid<TAB>home" per target user.
#   - as root: every local human account (UID >= UID_MIN from login.defs,
#     default 1000) with a real home under /home.
#   - as a user: just the current user (the MDM ran us in user context).
each_target_user() {
  if ! running_as_root; then
    printf '%s\t%s\t%s\n' "$(id -un)" "$(id -u)" "$HOME"
    return
  fi
  local uid_min
  uid_min=$(awk '/^UID_MIN/{print $2}' /etc/login.defs 2>/dev/null || true)
  [[ "$uid_min" =~ ^[0-9]+$ ]] || uid_min=1000
  local user uid home
  while IFS=: read -r user _ uid _ _ home _; do
    [[ "$uid" -ge "$uid_min" ]] || continue
    [[ -n "$home" && -d "$home" ]] || continue
    case "$home" in /home/*) ;; *) continue ;; esac
    printf '%s\t%s\t%s\n' "$user" "$uid" "$home"
  done < /etc/passwd
}

# True if this user has a reachable D-Bus session bus (a live login session).
user_has_session() {
  local uid
  if running_as_root; then
    uid=$(id -u "$1")
  else
    [[ "$1" == "$(id -un)" ]] || return 1
    uid=$(id -u)
  fi
  [[ -S "/run/user/${uid}/bus" ]]
}

# Home directory of a local user, from the passwd file.
user_home() {
  awk -v u="$1" -F: '$1 == u { print $6; exit }' /etc/passwd
}

# Run a file-scope command as the given user. Force HOME to the user's passwd
# home and drop leaked XDG_* vars, so pmg resolves per-user state under the
# right home even when sudo preserves the caller's HOME (env_keep).
run_user_file() {
  local user="$1"; shift
  if running_as_root; then
    local home; home=$(user_home "$user")
    sudo -u "$user" -H -- \
      env -u XDG_CONFIG_HOME -u XDG_CACHE_HOME -u XDG_DATA_HOME "HOME=$home" "$@"
  else
    "$@"
  fi
}

# Run a session-scope command (e.g. Secret Service) with the user's D-Bus
# session bus address set. Only call when user_has_session "$user" is true.
run_user_session() {
  local user="$1"; shift
  local uid home
  if running_as_root; then
    uid=$(id -u "$user")
    home=$(user_home "$user")
    sudo -u "$user" -H -- \
      env -u XDG_CONFIG_HOME -u XDG_CACHE_HOME -u XDG_DATA_HOME "HOME=$home" \
      "DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/${uid}/bus" "$@"
  else
    "$@"
  fi
}

# Per-user pmg state directories: env overrides win, else the XDG layout.
pmg_config_dir() { echo "${PMG_CONFIG_DIR:-$1/.config/safedep/pmg}"; }
pmg_cache_dir() { echo "${PMG_CACHE_DIR:-$1/.cache/safedep/pmg}"; }

# Absolute path to the pmg binary. root's PATH under an MDM is often minimal,
# so fall back to the machine-wide install location.
resolve_pmg() {
  local p
  p=$(command -v pmg 2>/dev/null) && { echo "$p"; return 0; }
  [[ -x /usr/local/bin/pmg ]] && { echo /usr/local/bin/pmg; return 0; }
  return 1
}

# Machine-wide globally managed config. When this file is present pmg treats
# it as authoritative and ignores every user's config. It must match the path
# pmg resolves on Linux.
readonly GLOBAL_CONFIG_DIR="/etc/safedep/pmg"
readonly GLOBAL_CONFIG_FILE="${GLOBAL_CONFIG_DIR}/config.yml"

# install_global_config <src> installs a bundled config.yml as the globally
# managed config: root-owned and 0644 so users can read but not modify it.
install_global_config() {
  local src="$1"
  log "Installing globally managed config to $GLOBAL_CONFIG_FILE"
  run_as_root install -d -m 0755 "$GLOBAL_CONFIG_DIR" || { warn "failed to create $GLOBAL_CONFIG_DIR (need root)"; return 1; }
  run_as_root install -m 0644 "$src" "$GLOBAL_CONFIG_FILE" || { warn "failed to install global config (need root)"; return 1; }
}

# remove_global_config removes the globally managed config when present,
# unless PMG_KEEP_GLOBAL_CONFIG is set.
remove_global_config() {
  if [[ -n "${PMG_KEEP_GLOBAL_CONFIG:-}" ]]; then
    [[ -e "$GLOBAL_CONFIG_FILE" ]] && log "Keeping globally managed config ($GLOBAL_CONFIG_FILE); PMG_KEEP_GLOBAL_CONFIG is set"
    return 0
  fi

  [[ -e "$GLOBAL_CONFIG_FILE" ]] || return 0
  log "Removing globally managed config $GLOBAL_CONFIG_FILE"
  run_as_root rm -f "$GLOBAL_CONFIG_FILE" || warn "failed to remove global config (need root)"
  run_as_root rmdir "$GLOBAL_CONFIG_DIR" 2>/dev/null || true
}
# pmg_setup_install_linux.sh — Install and configure PMG on a Linux machine.
#
# Deploy via JumpCloud or any MDM, alongside lib_linux.sh in the same
# directory. Run as root, it installs the machine-wide binary and configures
# every local user (config, aliases, shims). Cloud credentials are stored in
# the logged-in user's Secret Service keyring when SAFEDEP_API_KEY and
# SAFEDEP_TENANT_ID are set. Run as a user, it configures just that user. See
# lib_linux.sh for the model.
#
# Environment variables:
#   SAFEDEP_API_KEY    — SafeDep Cloud API key (with tenant ID, enables cloud sync)
#   SAFEDEP_TENANT_ID  — SafeDep Cloud tenant ID

set -euo pipefail

CLOUD_API_KEY="${SAFEDEP_API_KEY:-}"
CLOUD_TENANT_ID="${SAFEDEP_TENANT_ID:-}"
export -n CLOUD_API_KEY CLOUD_TENANT_ID
unset SAFEDEP_API_KEY SAFEDEP_TENANT_ID

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

require_linux

REPO="safedep/pmg"

load_embedded_cloud_credentials() {
  local embedded_api_key="${EMBEDDED_SAFEDEP_API_KEY_B64:-}"
  local embedded_tenant_id="${EMBEDDED_SAFEDEP_TENANT_ID_B64:-}"

  unset EMBEDDED_SAFEDEP_API_KEY_B64 EMBEDDED_SAFEDEP_TENANT_ID_B64

  if [[ -n "$CLOUD_API_KEY" && -n "$CLOUD_TENANT_ID" ]]; then
    return
  fi

  if [[ -z "$embedded_api_key" && -z "$embedded_tenant_id" ]]; then
    return
  fi

  if [[ -n "$CLOUD_API_KEY" || -n "$CLOUD_TENANT_ID" ]]; then
    echo "Error: SAFEDEP_API_KEY and SAFEDEP_TENANT_ID must be set together" >&2
    return 1
  fi

  if [[ -z "$embedded_api_key" || -z "$embedded_tenant_id" ]]; then
    echo "Error: embedded cloud credentials are incomplete" >&2
    return 1
  fi

  if ! CLOUD_API_KEY=$(printf '%s' "$embedded_api_key" | base64 -d); then
    echo "Error: could not decode embedded cloud API key" >&2
    return 1
  fi
  if ! CLOUD_TENANT_ID=$(printf '%s' "$embedded_tenant_id" | base64 -d); then
    echo "Error: could not decode embedded cloud tenant ID" >&2
    return 1
  fi
}

load_embedded_cloud_credentials || exit 1

install_via_release() {
  log "Installing pmg from GitHub releases"
  local install_dir="/usr/local/bin" tag arch asset url checksums_url expected actual

  case "$(uname -m)" in
    x86_64) arch="x86_64" ;;
    aarch64|arm64) arch="arm64" ;;
    *) echo "Error: unsupported architecture: $(uname -m)" >&2; exit 1 ;;
  esac

  tag=$(curl -fsSI -o /dev/null -w '%{redirect_url}' "https://github.com/${REPO}/releases/latest" | sed 's|.*/||') || true
  [[ -n "$tag" ]] || { echo "Error: could not determine latest release" >&2; exit 1; }
  log "Latest release: $tag"

  asset="pmg_Linux_${arch}.tar.gz"
  url="https://github.com/${REPO}/releases/download/${tag}/${asset}"
  checksums_url="https://github.com/${REPO}/releases/download/${tag}/checksums.txt"

  tmpdir=$(mktemp -d)
  trap 'rm -rf "$tmpdir"' EXIT

  log "Downloading $asset"
  curl -fsSL -o "${tmpdir}/${asset}" "$url"
  curl -fsSL -o "${tmpdir}/checksums.txt" "$checksums_url"

  expected=$(grep "  ${asset}$" "${tmpdir}/checksums.txt" | cut -d' ' -f1) || true
  [[ -n "$expected" ]] || { echo "Error: no checksum entry found for ${asset}" >&2; exit 1; }
  actual=$(sha256sum "${tmpdir}/${asset}" | cut -d' ' -f1)
  if [[ "$actual" != "$expected" ]]; then
    echo "Error: checksum mismatch for ${asset} (expected $expected, got $actual)" >&2
    exit 1
  fi
  log "Checksum verified"

  tar -xzf "${tmpdir}/${asset}" -C "${tmpdir}" pmg
  run_as_root install -m 755 "${tmpdir}/pmg" "${install_dir}/pmg"
  log "Installed pmg $tag to ${install_dir}/pmg"
}

install_via_release

PMG_BIN=$(resolve_pmg) || { echo "Error: pmg not found after install" >&2; exit 1; }
log "pmg installed: $("$PMG_BIN" version 2>/dev/null || echo unknown)"

install_requested_global_config() {
  local embedded_config="${EMBEDDED_GLOBAL_CONFIG_B64:-}"
  local embedded_config_tmp
  unset EMBEDDED_GLOBAL_CONFIG_B64

  if [[ -z "$embedded_config" ]]; then
    if [[ -f "${SCRIPT_DIR}/config.yml" ]]; then
      install_global_config "${SCRIPT_DIR}/config.yml"
    fi
    return
  fi

  embedded_config_tmp=$(mktemp "${TMPDIR:-/tmp}/pmg-embedded-config.XXXXXX") || {
    echo "Error: could not create temporary config file" >&2
    return 1
  }
  if ! printf '%s' "$embedded_config" | base64 -d > "$embedded_config_tmp"; then
    warn "failed to decode embedded global config"
    rm -f "$embedded_config_tmp" || warn "failed to remove temporary config file"
    return 1
  fi
  if ! install_global_config "$embedded_config_tmp"; then
    rm -f "$embedded_config_tmp" || warn "failed to remove temporary config file"
    return 1
  fi
  rm -f "$embedded_config_tmp" || warn "failed to remove temporary config file"
}

install_requested_global_config

if [[ -f "$GLOBAL_CONFIG_FILE" && -n "$CLOUD_API_KEY" && -n "$CLOUD_TENANT_ID" ]]; then
  log "Config is globally managed; set 'cloud.enabled: true' in the bundled config.yml to enable sync (per-user config is locked)"
fi

cloud_login() {
  local user="$1"

  # Single-quoted string is literal by design: bash -c runs it in the user's
  # session and $1 must expand there, not here.
  # shellcheck disable=SC2016
  printf '%s\0%s\0' "$CLOUD_API_KEY" "$CLOUD_TENANT_ID" |
    run_user_session "$user" /bin/bash -c '
      IFS= read -r -d "" SAFEDEP_API_KEY || exit 1
      IFS= read -r -d "" SAFEDEP_TENANT_ID || exit 1
      export SAFEDEP_API_KEY SAFEDEP_TENANT_ID
      exec "$1" cloud login --from-env
    ' _ "$PMG_BIN"
}

configure_user() {
  local user="$1"
  log "Configuring pmg for $user"
  run_user_file "$user" "$PMG_BIN" setup install || { warn "setup failed for $user"; return; }

  [[ -n "$CLOUD_API_KEY" && -n "$CLOUD_TENANT_ID" ]] || return 0
  if ! user_has_session "$user"; then
    log "  $user has no active session; run 'pmg cloud login' in their session to enable cloud sync"
    return
  fi
  # When config is globally managed, `cloud.enabled` comes from the global
  # file; per-user `config set` is refused. Per-user credentials still go to
  # the keyring.
  if [[ ! -f "$GLOBAL_CONFIG_FILE" ]]; then
    run_user_file "$user" "$PMG_BIN" config set cloud.enabled true || warn "could not enable cloud sync for $user"
  fi
  cloud_login "$user" || warn "cloud login failed for $user"
}

while IFS=$'\t' read -r user _ _; do
  configure_user "$user"
done < <(each_target_user)

unset CLOUD_API_KEY CLOUD_TENANT_ID

log "pmg setup complete"
