#!/bin/bash
# generate_standalone_lib.sh — engine shared by the per-OS standalone
# generators (generate_standalone_macos.sh, generate_standalone_linux.sh).
#
# Inline a shared lib into the MDM entry scripts to produce single-file
# variants for MDMs that accept one script per policy (e.g. Intune).
# Optionally embed a global config.yml and/or cloud credentials (from
# SAFEDEP_API_KEY/SAFEDEP_TENANT_ID) into the installer.
#
# This file is sourced by the wrappers; it is not executed directly. The
# wrapper sets the STANDALONE_* variables below, then calls
# generate_standalone_main "$@".

set -euo pipefail

# STANDALONE_CLOUD_* mirror the credentials SAFEDEP_API_KEY/SAFEDEP_TENANT_ID
# held when the generator starts, but never enter the environment, so child
# processes cannot inherit them. The wrapper captures and unsets them.
STANDALONE_CLOUD_API_KEY=""
STANDALONE_CLOUD_TENANT_ID=""

# The wrappers set these before calling generate_standalone_main.
#   STANDALONE_LIB_SOURCE        — shared lib inlined into every output
#   STANDALONE_INSTALL_SOURCE    — installer entry script
#   STANDALONE_UNINSTALL_SOURCE  — uninstaller entry script
#   STANDALONE_DEFAULT_OUTPUT_DIR
#   STANDALONE_INSTALL_NAME      — installer output file name
#   STANDALONE_UNINSTALL_NAME    — uninstaller output file name
#   STANDALONE_GENERATOR         — wrapper file name, used in the generated
#                                  comment so --check cmp stays byte-exact

generate_standalone_usage() {
  local generator="${STANDALONE_GENERATOR}"
  cat <<EOF
Usage:
  ${generator}
  ${generator} --output-dir <dir>
  ${generator} --config <config.yml> --output-dir <dir>
  ${generator} --embed-cloud-credentials --output-dir <dir>
  ${generator} --check
  ${generator} -h|--help
EOF
}

generate_standalone_die() {
  echo "Error: $*" >&2
  exit 1
}

generate_standalone_emit_entry() {
  local entry_source="$1"
  local shellcheck_line="$2"
  local source_line="$3"
  local line
  local first_line=1

  # shellcheck disable=SC2094
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$first_line" -eq 1 ]]; then
      first_line=0
      continue
    fi
    case "$line" in
      "$shellcheck_line")
        continue
        ;;
      "$source_line")
        if [[ "$entry_source" == "$STANDALONE_UNINSTALL_SOURCE" ]]; then
          printf ': "%s"\n' "\$SCRIPT_DIR"
        fi
        continue
        ;;
    esac
    printf '%s\n' "$line"
  done < "$entry_source"
}

generate_standalone_generate_script() {
  local entry_source="$1"
  local output_file="$2"
  local encoded_config="$3"
  local encoded_api_key="$4"
  local encoded_tenant_id="$5"
  local mode="$6"
  local size
  local shellcheck_line="# shellcheck source=${STANDALONE_LIB_SOURCE##*/}"
  local source_line
  # Single-quoted format is literal by design: ${SCRIPT_DIR} must appear
  # verbatim in the emitted output, not expand here.
  # shellcheck disable=SC2016
  printf -v source_line 'source "${SCRIPT_DIR}/%s"' "${STANDALONE_LIB_SOURCE##*/}"

  {
    printf '#!/bin/bash\n# Code generated by %s. Do not edit directly.\n' \
      "$STANDALONE_GENERATOR"
    awk 'NR > 1' "$STANDALONE_LIB_SOURCE"
    if [[ "$entry_source" == "$STANDALONE_INSTALL_SOURCE" ]]; then
      if [[ -n "$encoded_config" ]]; then
        printf "EMBEDDED_GLOBAL_CONFIG_B64='%s'\n" "$encoded_config"
      fi
      if [[ -n "$encoded_api_key" ]]; then
        printf "EMBEDDED_SAFEDEP_API_KEY_B64='%s'\n" "$encoded_api_key"
        printf "EMBEDDED_SAFEDEP_TENANT_ID_B64='%s'\n" "$encoded_tenant_id"
      fi
    fi
    generate_standalone_emit_entry "$entry_source" \
      "$shellcheck_line" "$source_line"
  } > "$output_file"

  chmod "$mode" "$output_file"
  bash -n "$output_file"
  if grep -qF "$source_line" "$output_file"; then
    generate_standalone_die \
      "$output_file still sources ${STANDALONE_LIB_SOURCE##*/}"
  fi

  size=$(wc -c < "$output_file")
  [[ "$size" -lt 1048576 ]] ||
    generate_standalone_die "$output_file must be smaller than 1048576 bytes"
}

generate_standalone_generate_scripts() {
  local output_dir="$1"
  local config_path="$2"
  local embed_cloud_credentials="$3"
  local encoded_config=""
  local encoded_api_key=""
  local encoded_tenant_id=""
  local install_mode="0755"
  local install_output
  local uninstall_output

  if [[ -n "$config_path" ]]; then
    [[ -f "$config_path" ]] ||
      generate_standalone_die "config file does not exist: $config_path"
    [[ -s "$config_path" ]] ||
      generate_standalone_die "config file is empty: $config_path"
    encoded_config=$(base64 < "$config_path" | tr -d '\r\n')
  fi

  if [[ "$embed_cloud_credentials" -eq 1 ]]; then
    [[ -n "$STANDALONE_CLOUD_API_KEY" ]] ||
      generate_standalone_die \
        "--embed-cloud-credentials requires non-empty SAFEDEP_API_KEY"
    [[ -n "$STANDALONE_CLOUD_TENANT_ID" ]] ||
      generate_standalone_die \
        "--embed-cloud-credentials requires non-empty SAFEDEP_TENANT_ID"
    encoded_api_key=$(
      printf '%s' "$STANDALONE_CLOUD_API_KEY" | base64 | tr -d '\r\n')
    encoded_tenant_id=$(
      printf '%s' "$STANDALONE_CLOUD_TENANT_ID" | base64 | tr -d '\r\n')
    install_mode="0700"
  fi
  unset STANDALONE_CLOUD_API_KEY STANDALONE_CLOUD_TENANT_ID

  mkdir -p "$output_dir"
  output_dir=$(cd "$output_dir" && pwd -P) ||
    generate_standalone_die "could not resolve output directory: $output_dir"
  install_output="${output_dir}/${STANDALONE_INSTALL_NAME}"
  uninstall_output="${output_dir}/${STANDALONE_UNINSTALL_NAME}"

  [[ ! -d "$install_output" ]] ||
    generate_standalone_die "output target is a directory: $install_output"
  [[ ! -d "$uninstall_output" ]] ||
    generate_standalone_die "output target is a directory: $uninstall_output"

  # Stage in WORK_DIR and publish only after both validate, so a failed
  # generation never rewrites existing artifacts.
  generate_standalone_generate_script \
    "$STANDALONE_UNINSTALL_SOURCE" "${WORK_DIR}/uninstall.sh" "" "" "" "0755"
  generate_standalone_generate_script \
    "$STANDALONE_INSTALL_SOURCE" "${WORK_DIR}/install.sh" "$encoded_config" \
    "$encoded_api_key" "$encoded_tenant_id" "$install_mode"
  mv "${WORK_DIR}/uninstall.sh" "$uninstall_output"
  mv "${WORK_DIR}/install.sh" "$install_output"

  if [[ "$embed_cloud_credentials" -eq 1 ]]; then
    echo "Warning: generated installer contains recoverable cloud credentials" >&2
  fi
}

generate_standalone_main() {
  local output_dir="$STANDALONE_DEFAULT_OUTPUT_DIR"
  local config_path=""
  local embed_cloud_credentials=0
  local check=0

  if [[ "$#" -eq 1 && ( "$1" == "-h" || "$1" == "--help" ) ]]; then
    generate_standalone_usage
    exit 0
  fi

  while [[ "$#" -gt 0 ]]; do
    case "$1" in
      --output-dir)
        [[ "${2:-}" != "" && "${2:-}" != -* ]] ||
          generate_standalone_die "--output-dir requires a directory"
        output_dir="$2"
        shift 2
        ;;
      --config)
        [[ "${2:-}" != "" && "${2:-}" != -* ]] ||
          generate_standalone_die "--config requires a file"
        config_path="$2"
        shift 2
        ;;
      --embed-cloud-credentials)
        embed_cloud_credentials=1
        shift
        ;;
      --check)
        check=1
        shift
        ;;
      -h|--help)
        generate_standalone_die "$1 must be used alone"
        ;;
      *)
        generate_standalone_die "unknown argument"
        ;;
    esac
  done

  for source in "$STANDALONE_LIB_SOURCE" "$STANDALONE_INSTALL_SOURCE" \
    "$STANDALONE_UNINSTALL_SOURCE"; do
    [[ -f "$source" ]] ||
      generate_standalone_die "missing source script: $source"
  done

  if [[ "$check" -eq 1 ]]; then
    [[ -z "$config_path" ]] ||
      generate_standalone_die "--check cannot be used with --config"
    [[ "$embed_cloud_credentials" -eq 0 ]] ||
      generate_standalone_die \
        "--check cannot be used with --embed-cloud-credentials"
    [[ "$output_dir" == "$STANDALONE_DEFAULT_OUTPUT_DIR" ]] ||
      generate_standalone_die "--check cannot be used with --output-dir"
    generate_standalone_generate_scripts "${WORK_DIR}/check" "" 0
    cmp "${WORK_DIR}/check/${STANDALONE_INSTALL_NAME}" \
      "${STANDALONE_DEFAULT_OUTPUT_DIR}/${STANDALONE_INSTALL_NAME}" >/dev/null ||
      generate_standalone_die "committed standalone installer is out of date"
    cmp "${WORK_DIR}/check/${STANDALONE_UNINSTALL_NAME}" \
      "${STANDALONE_DEFAULT_OUTPUT_DIR}/${STANDALONE_UNINSTALL_NAME}" >/dev/null ||
      generate_standalone_die "committed standalone uninstaller is out of date"
    echo "Generated standalone MDM scripts are current"
    exit 0
  fi

  if [[ "$output_dir" == "$STANDALONE_DEFAULT_OUTPUT_DIR" ]]; then
    [[ -z "$config_path" ]] ||
      generate_standalone_die "--config requires an explicit --output-dir"
    [[ "$embed_cloud_credentials" -eq 0 ]] ||
      generate_standalone_die \
        "--embed-cloud-credentials requires an explicit --output-dir"
  fi

  generate_standalone_generate_scripts \
    "$output_dir" "$config_path" "$embed_cloud_credentials"
}

WORK_DIR=$(mktemp -d "${TMPDIR:-/tmp}/pmg-standalone.XXXXXX")
trap 'rm -rf "$WORK_DIR"' EXIT
