#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
LIB_SOURCE="${SCRIPT_DIR}/lib_macos.sh"
INSTALL_SOURCE="${SCRIPT_DIR}/pmg_setup_install_macos.sh"
UNINSTALL_SOURCE="${SCRIPT_DIR}/pmg_uninstall_macos.sh"
DEFAULT_OUTPUT_DIR="${SCRIPT_DIR}/intune"
GENERATED_COMMENT="# Code generated by generate_intune_scripts.sh. Do not edit directly."
SHELLCHECK_LINE="# shellcheck source=lib_macos.sh"
SOURCE_LINE='source "${SCRIPT_DIR}/lib_macos.sh"'
CONFIG_MARKER="# Install the globally managed config if the package ships one. Done before the"
MAX_SCRIPT_SIZE=1048576

TEMP_PATH=""
CHECK_TEMP_DIR=""

cleanup() {
  if [[ -n "$TEMP_PATH" ]]; then
    rm -f "$TEMP_PATH"
  fi
  if [[ -n "$CHECK_TEMP_DIR" ]]; then
    rm -rf "$CHECK_TEMP_DIR"
  fi
}
trap cleanup EXIT

usage() {
  cat <<'EOF'
Usage:
  generate_intune_scripts.sh
  generate_intune_scripts.sh --output-dir <dir>
  generate_intune_scripts.sh --config <config.yml> --output-dir <dir>
  generate_intune_scripts.sh --check
  generate_intune_scripts.sh -h|--help
EOF
}

die() {
  echo "Error: $*" >&2
  exit 1
}

exact_line_count() {
  local file="$1"
  local line="$2"
  local count
  count=$(grep -Fxc "$line" "$file" || true)
  printf '%s\n' "$count"
}

validate_source() {
  local file="$1"
  local first_line

  [[ -f "$file" ]] || die "missing source script: $file"
  IFS= read -r first_line < "$file" || die "could not read source script: $file"
  [[ "$first_line" == "#!/bin/bash" ]] ||
    die "source script must start with #!/bin/bash: $file"
}

validate_entry_source() {
  local file="$1"
  local count

  validate_source "$file"
  count=$(exact_line_count "$file" "$SHELLCHECK_LINE")
  [[ "$count" -eq 1 ]] ||
    die "$file must contain the shellcheck source line exactly once"
  count=$(exact_line_count "$file" "$SOURCE_LINE")
  [[ "$count" -eq 1 ]] ||
    die "$file must contain the lib_macos.sh source line exactly once"
}

validate_sources() {
  validate_source "$LIB_SOURCE"
  validate_entry_source "$INSTALL_SOURCE"
  validate_entry_source "$UNINSTALL_SOURCE"
}

emit_embedded_config() {
  local encoded_config="$1"

  printf "EMBEDDED_GLOBAL_CONFIG_B64='%s'\n" "$encoded_config"
  cat <<'EOF'
embedded_config_tmp=$(mktemp) || {
  echo "Error: could not create temporary config file" >&2
  unset EMBEDDED_GLOBAL_CONFIG_B64
  exit 1
}
if ! printf '%s' "$EMBEDDED_GLOBAL_CONFIG_B64" | /usr/bin/base64 -D > "$embedded_config_tmp"; then
  warn "failed to decode embedded global config"
  rm -f "$embedded_config_tmp" || warn "failed to remove temporary config file"
  unset EMBEDDED_GLOBAL_CONFIG_B64 embedded_config_tmp
  exit 1
fi
if ! install_global_config "$embedded_config_tmp"; then
  rm -f "$embedded_config_tmp" || warn "failed to remove temporary config file"
  unset EMBEDDED_GLOBAL_CONFIG_B64 embedded_config_tmp
  exit 1
fi
if ! rm -f "$embedded_config_tmp"; then
  warn "failed to remove temporary config file"
  unset EMBEDDED_GLOBAL_CONFIG_B64 embedded_config_tmp
  exit 1
fi
unset EMBEDDED_GLOBAL_CONFIG_B64 embedded_config_tmp

EOF
}

emit_entry() {
  local entry_source="$1"
  local encoded_config="$2"
  local line
  local line_number=0
  local marker_count=0
  local -i embed_config=0

  if [[ -n "$encoded_config" && "$entry_source" == "$INSTALL_SOURCE" ]]; then
    embed_config=1
    marker_count=$(exact_line_count "$entry_source" "$CONFIG_MARKER")
    [[ "$marker_count" -eq 1 ]] ||
      die "$entry_source must contain the config marker exactly once"
  fi

  while IFS= read -r line || [[ -n "$line" ]]; do
    line_number=$((line_number + 1))
    if [[ "$line_number" -eq 1 ]]; then
      continue
    fi
    if [[ "$line" == "$SHELLCHECK_LINE" ]]; then
      continue
    fi
    if [[ "$line" == "$SOURCE_LINE" ]]; then
      if [[ "$entry_source" == "$UNINSTALL_SOURCE" ]]; then
        printf ': "$SCRIPT_DIR"\n'
      fi
      continue
    fi
    if [[ "$embed_config" -eq 1 && "$line" == "$CONFIG_MARKER" ]]; then
      emit_embedded_config "$encoded_config"
    fi
    printf '%s\n' "$line"
  done < "$entry_source"
}

validate_generated_script() {
  local file="$1"
  local count
  local size

  chmod 0755 "$file"
  bash -n "$file"

  count=$(grep -c '^#!' "$file" || true)
  [[ "$count" -eq 1 ]] || die "$file must contain exactly one shebang"
  count=$(exact_line_count "$file" "$SOURCE_LINE")
  [[ "$count" -eq 0 ]] || die "$file still sources lib_macos.sh"

  size=$(wc -c < "$file")
  [[ "$size" -lt "$MAX_SCRIPT_SIZE" ]] ||
    die "$file must be smaller than $MAX_SCRIPT_SIZE bytes"
}

generate_script() {
  local entry_source="$1"
  local output_file="$2"
  local encoded_config="$3"
  local first_line
  local temp_file

  [[ ! -d "$output_file" ]] ||
    die "output target is a directory; remove it before generating: $output_file"

  IFS= read -r first_line < "$LIB_SOURCE"
  temp_file=$(mktemp "${output_file}.tmp.XXXXXX")
  TEMP_PATH="$temp_file"

  {
    printf '%s\n' "$first_line"
    printf '%s\n' "$GENERATED_COMMENT"
    awk 'NR > 1' "$LIB_SOURCE"
    emit_entry "$entry_source" "$encoded_config"
  } > "$temp_file"

  validate_generated_script "$temp_file"
  mv "$temp_file" "$output_file"
  TEMP_PATH=""
}

generate_scripts() {
  local output_dir="$1"
  local config_path="$2"
  local encoded_config=""

  if [[ -n "$config_path" ]]; then
    [[ -f "$config_path" ]] || die "config file does not exist: $config_path"
    [[ -s "$config_path" ]] || die "config file is empty: $config_path"
    encoded_config=$(base64 < "$config_path" | tr -d '\r\n')
    [[ -n "$encoded_config" ]] || die "could not encode config file: $config_path"
  fi

  mkdir -p "$output_dir"
  generate_script "$INSTALL_SOURCE" "${output_dir}/pmg_setup_install_macos.sh" "$encoded_config"
  generate_script "$UNINSTALL_SOURCE" "${output_dir}/pmg_uninstall_macos.sh" ""
}

output_dir="$DEFAULT_OUTPUT_DIR"
output_dir_set=0
config_path=""
config_set=0
check=0

if [[ "$#" -eq 1 && ( "$1" == "-h" || "$1" == "--help" ) ]]; then
  usage
  exit 0
fi

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --output-dir)
      [[ "$output_dir_set" -eq 0 ]] || die "--output-dir may only be specified once"
      [[ "$#" -ge 2 && -n "$2" && "$2" != -* ]] || die "--output-dir requires a directory"
      output_dir="$2"
      output_dir_set=1
      shift 2
      ;;
    --config)
      [[ "$config_set" -eq 0 ]] || die "--config may only be specified once"
      [[ "$#" -ge 2 && -n "$2" && "$2" != -* ]] || die "--config requires a file"
      config_path="$2"
      config_set=1
      shift 2
      ;;
    --check)
      [[ "$check" -eq 0 ]] || die "--check may only be specified once"
      check=1
      shift
      ;;
    -h|--help)
      die "$1 must be used alone"
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

validate_sources

if [[ "$check" -eq 1 ]]; then
  [[ "$config_set" -eq 0 ]] || die "--check cannot be used with --config"
  [[ "$output_dir_set" -eq 0 ]] || die "--check cannot be used with --output-dir"
  CHECK_TEMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/pmg-intune-check.XXXXXX")
  generate_scripts "$CHECK_TEMP_DIR" ""
  cmp "${CHECK_TEMP_DIR}/pmg_setup_install_macos.sh" \
    "${DEFAULT_OUTPUT_DIR}/pmg_setup_install_macos.sh" >/dev/null ||
    die "committed Intune installer is out of date"
  cmp "${CHECK_TEMP_DIR}/pmg_uninstall_macos.sh" \
    "${DEFAULT_OUTPUT_DIR}/pmg_uninstall_macos.sh" >/dev/null ||
    die "committed Intune uninstaller is out of date"
  echo "Generated Intune scripts are current"
  exit 0
fi

if [[ "$config_set" -eq 1 && "$output_dir_set" -eq 0 ]]; then
  die "--config requires an explicit --output-dir"
fi

generate_scripts "$output_dir" "$config_path"
