#!/bin/bash
set -euo pipefail

CLOUD_API_KEY="${SAFEDEP_API_KEY:-}"
CLOUD_TENANT_ID="${SAFEDEP_TENANT_ID:-}"
export -n CLOUD_API_KEY CLOUD_TENANT_ID
unset SAFEDEP_API_KEY SAFEDEP_TENANT_ID

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
LIB_SOURCE="${SCRIPT_DIR}/lib_macos.sh"
INSTALL_SOURCE="${SCRIPT_DIR}/pmg_setup_install_macos.sh"
UNINSTALL_SOURCE="${SCRIPT_DIR}/pmg_uninstall_macos.sh"
DEFAULT_OUTPUT_DIR="${SCRIPT_DIR}/standalone"
GENERATED_COMMENT="# Code generated by generate_standalone_scripts.sh. Do not edit directly."
SHELLCHECK_LINE="# shellcheck source=lib_macos.sh"
SOURCE_LINE="source \"\${SCRIPT_DIR}/lib_macos.sh\""
MAX_SCRIPT_SIZE=1048576

TEMP_PATH=""
CHECK_TEMP_DIR=""
STAGING_DIR=""

cleanup() {
  if [[ -n "$TEMP_PATH" ]]; then
    rm -f "$TEMP_PATH"
  fi
  if [[ -n "$CHECK_TEMP_DIR" ]]; then
    rm -rf "$CHECK_TEMP_DIR"
  fi
  if [[ -n "$STAGING_DIR" ]]; then
    rm -rf "$STAGING_DIR"
  fi
}
trap cleanup EXIT

usage() {
  cat <<'EOF'
Usage:
  generate_standalone_scripts.sh
  generate_standalone_scripts.sh --output-dir <dir>
  generate_standalone_scripts.sh --config <config.yml> --output-dir <dir>
  generate_standalone_scripts.sh --embed-cloud-credentials --output-dir <dir>
  generate_standalone_scripts.sh --check
  generate_standalone_scripts.sh -h|--help
EOF
}

die() {
  echo "Error: $*" >&2
  exit 1
}

exact_line_count() {
  local file="$1"
  local line="$2"
  local count
  count=$(grep -Fxc "$line" "$file" || true)
  printf '%s\n' "$count"
}

validate_source() {
  local file="$1"
  local first_line

  [[ -f "$file" ]] || die "missing source script: $file"
  IFS= read -r first_line < "$file" || die "could not read source script: $file"
  [[ "$first_line" == "#!/bin/bash" ]] ||
    die "source script must start with #!/bin/bash: $file"
}

validate_entry_source() {
  local file="$1"
  local count

  validate_source "$file"
  count=$(exact_line_count "$file" "$SHELLCHECK_LINE")
  [[ "$count" -eq 1 ]] ||
    die "$file must contain the shellcheck source line exactly once"
  count=$(exact_line_count "$file" "$SOURCE_LINE")
  [[ "$count" -eq 1 ]] ||
    die "$file must contain the lib_macos.sh source line exactly once"
}

validate_sources() {
  validate_source "$LIB_SOURCE"
  validate_entry_source "$INSTALL_SOURCE"
  validate_entry_source "$UNINSTALL_SOURCE"
}

emit_embedded_config() {
  local encoded_config="$1"

  printf "EMBEDDED_GLOBAL_CONFIG_B64='%s'\n" "$encoded_config"
}

emit_embedded_credentials() {
  local encoded_api_key="$1"
  local encoded_tenant_id="$2"

  printf "EMBEDDED_SAFEDEP_API_KEY_B64='%s'\n" "$encoded_api_key"
  printf "EMBEDDED_SAFEDEP_TENANT_ID_B64='%s'\n" "$encoded_tenant_id"
}

emit_entry() {
  local entry_source="$1"
  local line
  local line_number=0

  # shellcheck disable=SC2094
  while IFS= read -r line || [[ -n "$line" ]]; do
    line_number=$((line_number + 1))
    if [[ "$line_number" -eq 1 ]]; then
      continue
    fi
    if [[ "$line" == "$SHELLCHECK_LINE" ]]; then
      continue
    fi
    if [[ "$line" == "$SOURCE_LINE" ]]; then
      if [[ "$entry_source" == "$UNINSTALL_SOURCE" ]]; then
        printf ': "%s"\n' "\$SCRIPT_DIR"
      fi
      continue
    fi
    printf '%s\n' "$line"
  done < "$entry_source"
}

validate_generated_script() {
  local file="$1"
  local mode="$2"
  local count
  local size

  chmod "$mode" "$file"
  bash -n "$file"

  count=$(grep -c '^#!' "$file" || true)
  [[ "$count" -eq 1 ]] || die "$file must contain exactly one shebang"
  count=$(exact_line_count "$file" "$SOURCE_LINE")
  [[ "$count" -eq 0 ]] || die "$file still sources lib_macos.sh"

  size=$(wc -c < "$file")
  [[ "$size" -lt "$MAX_SCRIPT_SIZE" ]] ||
    die "$file must be smaller than $MAX_SCRIPT_SIZE bytes"
}

validate_output_target() {
  local output_file="$1"

  [[ ! -d "$output_file" ]] ||
    die "output target is a directory; remove it before generating: $output_file"
}

generate_script() {
  local entry_source="$1"
  local output_file="$2"
  local encoded_config="$3"
  local encoded_api_key="$4"
  local encoded_tenant_id="$5"
  local mode="$6"
  local first_line
  local temp_file

  validate_output_target "$output_file"

  IFS= read -r first_line < "$LIB_SOURCE"
  temp_file=$(mktemp "${output_file}.tmp.XXXXXX")
  TEMP_PATH="$temp_file"

  {
    printf '%s\n' "$first_line"
    printf '%s\n' "$GENERATED_COMMENT"
    awk 'NR > 1' "$LIB_SOURCE"
    if [[ "$entry_source" == "$INSTALL_SOURCE" ]]; then
      if [[ -n "$encoded_config" ]]; then
        emit_embedded_config "$encoded_config"
      fi
      if [[ -n "$encoded_api_key" ]]; then
        emit_embedded_credentials "$encoded_api_key" "$encoded_tenant_id"
      fi
    fi
    emit_entry "$entry_source"
  } > "$temp_file"

  validate_generated_script "$temp_file" "$mode"
  mv "$temp_file" "$output_file"
  TEMP_PATH=""
}

generate_scripts() {
  local output_dir="$1"
  local config_path="$2"
  local embed_cloud_credentials="$3"
  local encoded_config=""
  local encoded_api_key=""
  local encoded_tenant_id=""
  local install_mode="0755"
  local resolved_output_dir
  local install_output
  local uninstall_output
  local staged_install
  local staged_uninstall

  if [[ -n "$config_path" ]]; then
    [[ -f "$config_path" ]] || die "config file does not exist: $config_path"
    [[ -s "$config_path" ]] || die "config file is empty: $config_path"
    encoded_config=$(base64 < "$config_path" | tr -d '\r\n')
    [[ -n "$encoded_config" ]] || die "could not encode config file: $config_path"
  fi

  if [[ "$embed_cloud_credentials" -eq 1 ]]; then
    [[ -n "$CLOUD_API_KEY" ]] ||
      die "--embed-cloud-credentials requires non-empty SAFEDEP_API_KEY"
    [[ -n "$CLOUD_TENANT_ID" ]] ||
      die "--embed-cloud-credentials requires non-empty SAFEDEP_TENANT_ID"
    encoded_api_key=$(printf '%s' "$CLOUD_API_KEY" | base64 | tr -d '\r\n')
    encoded_tenant_id=$(printf '%s' "$CLOUD_TENANT_ID" | base64 | tr -d '\r\n')
    [[ -n "$encoded_api_key" ]] || die "could not encode SAFEDEP_API_KEY"
    [[ -n "$encoded_tenant_id" ]] || die "could not encode SAFEDEP_TENANT_ID"
    install_mode="0700"
  fi
  unset CLOUD_API_KEY CLOUD_TENANT_ID

  mkdir -p "$output_dir"
  resolved_output_dir=$(cd "$output_dir" && pwd -P) ||
    die "could not resolve output directory: $output_dir"
  install_output="${resolved_output_dir}/pmg_setup_install_macos_standalone.sh"
  uninstall_output="${resolved_output_dir}/pmg_uninstall_macos_standalone.sh"

  validate_output_target "$install_output"
  validate_output_target "$uninstall_output"

  STAGING_DIR=$(mktemp -d "${resolved_output_dir}/.pmg-standalone-stage.XXXXXX")
  staged_install="${STAGING_DIR}/pmg_setup_install_macos_standalone.sh"
  staged_uninstall="${STAGING_DIR}/pmg_uninstall_macos_standalone.sh"

  generate_script "$UNINSTALL_SOURCE" "$staged_uninstall" "" "" "" "0755"
  generate_script "$INSTALL_SOURCE" "$staged_install" "$encoded_config" \
    "$encoded_api_key" "$encoded_tenant_id" "$install_mode"
  mv "$staged_uninstall" "$uninstall_output"
  mv "$staged_install" "$install_output"
  rmdir "$STAGING_DIR"
  STAGING_DIR=""

  if [[ "$embed_cloud_credentials" -eq 1 ]]; then
    echo "Warning: generated installer contains recoverable cloud credentials" >&2
  fi
}

output_dir="$DEFAULT_OUTPUT_DIR"
output_dir_set=0
config_path=""
config_set=0
embed_cloud_credentials=0
check=0

if [[ "$#" -eq 1 && ( "$1" == "-h" || "$1" == "--help" ) ]]; then
  usage
  exit 0
fi

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --output-dir)
      [[ "$output_dir_set" -eq 0 ]] || die "--output-dir may only be specified once"
      [[ "$#" -ge 2 && -n "$2" && "$2" != -* ]] || die "--output-dir requires a directory"
      output_dir="$2"
      output_dir_set=1
      shift 2
      ;;
    --config)
      [[ "$config_set" -eq 0 ]] || die "--config may only be specified once"
      [[ "$#" -ge 2 && -n "$2" && "$2" != -* ]] || die "--config requires a file"
      config_path="$2"
      config_set=1
      shift 2
      ;;
    --embed-cloud-credentials)
      [[ "$embed_cloud_credentials" -eq 0 ]] ||
        die "--embed-cloud-credentials may only be specified once"
      embed_cloud_credentials=1
      shift
      ;;
    --check)
      [[ "$check" -eq 0 ]] || die "--check may only be specified once"
      check=1
      shift
      ;;
    -h|--help)
      die "$1 must be used alone"
      ;;
    *)
      die "unknown argument"
      ;;
  esac
done

validate_sources

if [[ "$check" -eq 1 ]]; then
  [[ "$config_set" -eq 0 ]] || die "--check cannot be used with --config"
  [[ "$embed_cloud_credentials" -eq 0 ]] ||
    die "--check cannot be used with --embed-cloud-credentials"
  [[ "$output_dir_set" -eq 0 ]] || die "--check cannot be used with --output-dir"
  CHECK_TEMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/pmg-standalone-check.XXXXXX")
  generate_scripts "$CHECK_TEMP_DIR" "" 0
  cmp "${CHECK_TEMP_DIR}/pmg_setup_install_macos_standalone.sh" \
    "${DEFAULT_OUTPUT_DIR}/pmg_setup_install_macos_standalone.sh" >/dev/null ||
    die "committed standalone installer is out of date"
  cmp "${CHECK_TEMP_DIR}/pmg_uninstall_macos_standalone.sh" \
    "${DEFAULT_OUTPUT_DIR}/pmg_uninstall_macos_standalone.sh" >/dev/null ||
    die "committed standalone uninstaller is out of date"
  echo "Generated standalone MDM scripts are current"
  exit 0
fi

if [[ "$output_dir_set" -eq 0 ]]; then
  [[ "$config_set" -eq 0 ]] || die "--config requires an explicit --output-dir"
  [[ "$embed_cloud_credentials" -eq 0 ]] ||
    die "--embed-cloud-credentials requires an explicit --output-dir"
fi

generate_scripts "$output_dir" "$config_path" "$embed_cloud_credentials"
