#!/bin/bash
# generate_standalone_scripts.sh — Inline lib_macos.sh into the MDM entry
# scripts to produce single-file variants for MDMs that accept one script per
# policy (e.g. Intune). Optionally embed a global config.yml and/or cloud
# credentials (from SAFEDEP_API_KEY/SAFEDEP_TENANT_ID) into the installer.

set -euo pipefail

CLOUD_API_KEY="${SAFEDEP_API_KEY:-}"
CLOUD_TENANT_ID="${SAFEDEP_TENANT_ID:-}"
export -n CLOUD_API_KEY CLOUD_TENANT_ID
unset SAFEDEP_API_KEY SAFEDEP_TENANT_ID

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
LIB_SOURCE="${SCRIPT_DIR}/lib_macos.sh"
INSTALL_SOURCE="${SCRIPT_DIR}/pmg_setup_install_macos.sh"
UNINSTALL_SOURCE="${SCRIPT_DIR}/pmg_uninstall_macos.sh"
DEFAULT_OUTPUT_DIR="${SCRIPT_DIR}/standalone"
GENERATED_COMMENT="# Code generated by generate_standalone_scripts.sh. Do not edit directly."
SHELLCHECK_DISABLE="# shellcheck disable=SC2016"
SHELLCHECK_LINE="# shellcheck source=lib_macos.sh"
SOURCE_LINE="source \"\${SCRIPT_DIR}/lib_macos.sh\""
MAX_SCRIPT_SIZE=1048576

WORK_DIR=$(mktemp -d "${TMPDIR:-/tmp}/pmg-standalone.XXXXXX")
trap 'rm -rf "$WORK_DIR"' EXIT

usage() {
  cat <<'EOF'
Usage:
  generate_standalone_scripts.sh
  generate_standalone_scripts.sh --output-dir <dir>
  generate_standalone_scripts.sh --config <config.yml> --output-dir <dir>
  generate_standalone_scripts.sh --embed-cloud-credentials --output-dir <dir>
  generate_standalone_scripts.sh --check
  generate_standalone_scripts.sh -h|--help
EOF
}

die() {
  echo "Error: $*" >&2
  exit 1
}

emit_entry() {
  local entry_source="$1"
  local line
  local first_line=1

  # shellcheck disable=SC2094
  while IFS= read -r line || [[ -n "$line" ]]; do
    if [[ "$first_line" -eq 1 ]]; then
      first_line=0
      continue
    fi
    case "$line" in
      "$SHELLCHECK_LINE")
        continue
        ;;
      "$SOURCE_LINE")
        if [[ "$entry_source" == "$UNINSTALL_SOURCE" ]]; then
          printf ': "%s"\n' "\$SCRIPT_DIR"
        fi
        continue
        ;;
    esac
    printf '%s\n' "$line"
  done < "$entry_source"
}

generate_script() {
  local entry_source="$1"
  local output_file="$2"
  local encoded_config="$3"
  local encoded_api_key="$4"
  local encoded_tenant_id="$5"
  local mode="$6"
  local size

  {
    printf '#!/bin/bash\n%s\n%s\n' "$GENERATED_COMMENT" "$SHELLCHECK_DISABLE"
    awk 'NR > 1' "$LIB_SOURCE"
    if [[ "$entry_source" == "$INSTALL_SOURCE" ]]; then
      if [[ -n "$encoded_config" ]]; then
        printf "EMBEDDED_GLOBAL_CONFIG_B64='%s'\n" "$encoded_config"
      fi
      if [[ -n "$encoded_api_key" ]]; then
        printf "EMBEDDED_SAFEDEP_API_KEY_B64='%s'\n" "$encoded_api_key"
        printf "EMBEDDED_SAFEDEP_TENANT_ID_B64='%s'\n" "$encoded_tenant_id"
      fi
    fi
    emit_entry "$entry_source"
  } > "$output_file"

  chmod "$mode" "$output_file"
  bash -n "$output_file"
  if grep -qF "$SOURCE_LINE" "$output_file"; then
    die "$output_file still sources lib_macos.sh"
  fi

  size=$(wc -c < "$output_file")
  [[ "$size" -lt "$MAX_SCRIPT_SIZE" ]] ||
    die "$output_file must be smaller than $MAX_SCRIPT_SIZE bytes"
}

generate_scripts() {
  local output_dir="$1"
  local config_path="$2"
  local embed_cloud_credentials="$3"
  local encoded_config=""
  local encoded_api_key=""
  local encoded_tenant_id=""
  local install_mode="0755"
  local install_output
  local uninstall_output

  if [[ -n "$config_path" ]]; then
    [[ -f "$config_path" ]] || die "config file does not exist: $config_path"
    [[ -s "$config_path" ]] || die "config file is empty: $config_path"
    encoded_config=$(base64 < "$config_path" | tr -d '\r\n')
  fi

  if [[ "$embed_cloud_credentials" -eq 1 ]]; then
    [[ -n "$CLOUD_API_KEY" ]] ||
      die "--embed-cloud-credentials requires non-empty SAFEDEP_API_KEY"
    [[ -n "$CLOUD_TENANT_ID" ]] ||
      die "--embed-cloud-credentials requires non-empty SAFEDEP_TENANT_ID"
    encoded_api_key=$(printf '%s' "$CLOUD_API_KEY" | base64 | tr -d '\r\n')
    encoded_tenant_id=$(printf '%s' "$CLOUD_TENANT_ID" | base64 | tr -d '\r\n')
    install_mode="0700"
  fi
  unset CLOUD_API_KEY CLOUD_TENANT_ID

  mkdir -p "$output_dir"
  output_dir=$(cd "$output_dir" && pwd -P) ||
    die "could not resolve output directory: $output_dir"
  install_output="${output_dir}/pmg_setup_install_macos_standalone.sh"
  uninstall_output="${output_dir}/pmg_uninstall_macos_standalone.sh"

  [[ ! -d "$install_output" ]] ||
    die "output target is a directory: $install_output"
  [[ ! -d "$uninstall_output" ]] ||
    die "output target is a directory: $uninstall_output"

  # Stage in WORK_DIR and publish only after both validate, so a failed
  # generation never rewrites existing artifacts.
  generate_script "$UNINSTALL_SOURCE" "${WORK_DIR}/uninstall.sh" "" "" "" "0755"
  generate_script "$INSTALL_SOURCE" "${WORK_DIR}/install.sh" "$encoded_config" \
    "$encoded_api_key" "$encoded_tenant_id" "$install_mode"
  mv "${WORK_DIR}/uninstall.sh" "$uninstall_output"
  mv "${WORK_DIR}/install.sh" "$install_output"

  if [[ "$embed_cloud_credentials" -eq 1 ]]; then
    echo "Warning: generated installer contains recoverable cloud credentials" >&2
  fi
}

output_dir="$DEFAULT_OUTPUT_DIR"
config_path=""
embed_cloud_credentials=0
check=0

if [[ "$#" -eq 1 && ( "$1" == "-h" || "$1" == "--help" ) ]]; then
  usage
  exit 0
fi

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --output-dir)
      [[ -n "$2" && "$2" != -* ]] || die "--output-dir requires a directory"
      output_dir="$2"
      shift 2
      ;;
    --config)
      [[ -n "$2" && "$2" != -* ]] || die "--config requires a file"
      config_path="$2"
      shift 2
      ;;
    --embed-cloud-credentials)
      embed_cloud_credentials=1
      shift
      ;;
    --check)
      check=1
      shift
      ;;
    -h|--help)
      die "$1 must be used alone"
      ;;
    *)
      die "unknown argument"
      ;;
  esac
done

for source in "$LIB_SOURCE" "$INSTALL_SOURCE" "$UNINSTALL_SOURCE"; do
  [[ -f "$source" ]] || die "missing source script: $source"
done

if [[ "$check" -eq 1 ]]; then
  [[ -z "$config_path" ]] || die "--check cannot be used with --config"
  [[ "$embed_cloud_credentials" -eq 0 ]] ||
    die "--check cannot be used with --embed-cloud-credentials"
  [[ "$output_dir" == "$DEFAULT_OUTPUT_DIR" ]] || die "--check cannot be used with --output-dir"
  generate_scripts "${WORK_DIR}/check" "" 0
  cmp "${WORK_DIR}/check/pmg_setup_install_macos_standalone.sh" \
    "${DEFAULT_OUTPUT_DIR}/pmg_setup_install_macos_standalone.sh" >/dev/null ||
    die "committed standalone installer is out of date"
  cmp "${WORK_DIR}/check/pmg_uninstall_macos_standalone.sh" \
    "${DEFAULT_OUTPUT_DIR}/pmg_uninstall_macos_standalone.sh" >/dev/null ||
    die "committed standalone uninstaller is out of date"
  echo "Generated standalone MDM scripts are current"
  exit 0
fi

if [[ "$output_dir" == "$DEFAULT_OUTPUT_DIR" ]]; then
  [[ -z "$config_path" ]] || die "--config requires an explicit --output-dir"
  [[ "$embed_cloud_credentials" -eq 0 ]] ||
    die "--embed-cloud-credentials requires an explicit --output-dir"
fi

generate_scripts "$output_dir" "$config_path" "$embed_cloud_credentials"
