#!/bin/bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
GENERATOR="${SCRIPT_DIR}/generate_standalone_scripts.sh"
TEST_ROOT=$(mktemp -d)

trap 'rm -rf "$TEST_ROOT"' EXIT

fail() {
  echo "FAIL: $*" >&2
  exit 1
}

assert_file() {
  [[ -f "$1" ]] || fail "missing file: $1"
}

assert_executable() {
  [[ -x "$1" ]] || fail "file is not executable: $1"
}

assert_contains() {
  grep -Fq "$2" "$1" || fail "$1 does not contain: $2"
}

assert_not_contains() {
  local status
  if grep -Fq "$2" "$1"; then
    fail "$1 unexpectedly contains: $2"
  else
    status=$?
    [[ "$status" -eq 1 ]] || fail "could not inspect file: $1"
  fi
}

assert_one_shebang() {
  local count
  count=$(grep -c '^#!' "$1" || true)
  [[ "$count" -eq 1 ]] || fail "$1 must contain exactly one shebang"
}

assert_fails() {
  if "$@"; then
    fail "command should fail: $*"
  fi
}

OUT_ONE="${TEST_ROOT}/one"
OUT_TWO="${TEST_ROOT}/two"

"$GENERATOR" --output-dir "$OUT_ONE"
"$GENERATOR" --output-dir "$OUT_TWO"

INSTALL_ONE="${OUT_ONE}/pmg_setup_install_macos_standalone.sh"
UNINSTALL_ONE="${OUT_ONE}/pmg_uninstall_macos_standalone.sh"
INSTALL_TWO="${OUT_TWO}/pmg_setup_install_macos_standalone.sh"
UNINSTALL_TWO="${OUT_TWO}/pmg_uninstall_macos_standalone.sh"

for output in "$INSTALL_ONE" "$UNINSTALL_ONE" "$INSTALL_TWO" "$UNINSTALL_TWO"; do
  assert_file "$output"
  assert_executable "$output"
  bash -n "$output"
  assert_one_shebang "$output"
  assert_not_contains "$output" "source \"\${SCRIPT_DIR}/lib_macos.sh\""
  assert_contains "$output" 'require_macos()'
  assert_contains "$output" 'each_target_user()'
  assert_contains "$output" 'run_user_session()'
  assert_contains "$output" '# Code generated by generate_standalone_scripts.sh. Do not edit directly.'
done

cmp "$INSTALL_ONE" "$INSTALL_TWO"
cmp "$UNINSTALL_ONE" "$UNINSTALL_TWO"

assert_contains "$INSTALL_ONE" 'install_via_release()'
assert_contains "$INSTALL_ONE" 'configure_user()'
assert_contains "$UNINSTALL_ONE" 'remove_user_state()'
assert_contains "$UNINSTALL_ONE" 'remove_binary()'

DIRECTORY_TARGET_OUT="${TEST_ROOT}/directory-target"
mkdir -p "${DIRECTORY_TARGET_OUT}/pmg_setup_install_macos_standalone.sh"
assert_fails "$GENERATOR" --output-dir "$DIRECTORY_TARGET_OUT"

SOURCE_OVERWRITE_FIXTURE="${TEST_ROOT}/source-overwrite"
mkdir -p "$SOURCE_OVERWRITE_FIXTURE"
cp "$GENERATOR" \
  "${SCRIPT_DIR}/lib_macos.sh" \
  "${SCRIPT_DIR}/pmg_setup_install_macos.sh" \
  "${SCRIPT_DIR}/pmg_uninstall_macos.sh" \
  "$SOURCE_OVERWRITE_FIXTURE"
"${SOURCE_OVERWRITE_FIXTURE}/generate_standalone_scripts.sh" \
  --output-dir "$SOURCE_OVERWRITE_FIXTURE"
cmp "${SCRIPT_DIR}/pmg_setup_install_macos.sh" \
  "${SOURCE_OVERWRITE_FIXTURE}/pmg_setup_install_macos.sh"
cmp "${SCRIPT_DIR}/pmg_uninstall_macos.sh" \
  "${SOURCE_OVERWRITE_FIXTURE}/pmg_uninstall_macos.sh"
assert_file "${SOURCE_OVERWRITE_FIXTURE}/pmg_setup_install_macos_standalone.sh"
assert_file "${SOURCE_OVERWRITE_FIXTURE}/pmg_uninstall_macos_standalone.sh"

CONFIG="${TEST_ROOT}/config.yml"
cat > "$CONFIG" <<'EOF'
global_lockdown: true
cloud:
  enabled: true
EOF

CONFIG_OUT="${TEST_ROOT}/configured"
"$GENERATOR" --config "$CONFIG" --output-dir "$CONFIG_OUT"

CONFIG_INSTALL="${CONFIG_OUT}/pmg_setup_install_macos_standalone.sh"
CONFIG_UNINSTALL="${CONFIG_OUT}/pmg_uninstall_macos_standalone.sh"

assert_contains "$CONFIG_INSTALL" 'EMBEDDED_GLOBAL_CONFIG_B64='
assert_not_contains "$CONFIG_UNINSTALL" 'EMBEDDED_GLOBAL_CONFIG_B64='

embedded_line=$(grep -Fnm1 'EMBEDDED_GLOBAL_CONFIG_B64=' "$CONFIG_INSTALL" | cut -d: -f1)
setup_line=$(grep -Fnm1 'configure_user()' "$CONFIG_INSTALL" | cut -d: -f1)
[[ "$embedded_line" -lt "$setup_line" ]] ||
  fail "embedded config must appear before per-user setup"

assert_fails "$GENERATOR" \
  --config "${TEST_ROOT}/missing.yml" \
  --output-dir "${TEST_ROOT}/missing-output"

EMPTY_CONFIG="${TEST_ROOT}/empty.yml"
: > "$EMPTY_CONFIG"
assert_fails "$GENERATOR" \
  --config "$EMPTY_CONFIG" \
  --output-dir "${TEST_ROOT}/empty-output"

assert_fails "$GENERATOR" --config "$CONFIG"

echo "PASS"
