name: install npm packages
description: Installs npm packages

runs:
  using: composite
  steps:
    - name: Install Yarn
      run: npm install -g yarn
      shell: bash

    - name: install packages
      run: npm install safedep-test-pkg
      shell: bash
