#!/bin/bash
# generate_standalone_windows_test.sh - test generate_standalone_windows.sh.
# The Windows scripts are PowerShell, so the shared generator test does not
# cover them. Runs on any host with bash. With pwsh on a non-Windows host,
# it also checks that every Windows script refuses to run there.
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)

# shellcheck source=test_lib.sh
source "${SCRIPT_DIR}/lib/test_lib.sh"

TEST_API_KEY="pmg-generator-test-api-key"
TEST_TENANT_ID="pmg-generator-test-tenant"
GENERATOR="${SCRIPT_DIR}/generate_standalone_windows.sh"
INSTALL_NAME="pmg_setup_install_windows_standalone.ps1"
UNINSTALL_NAME="pmg_uninstall_windows_standalone.ps1"
TEST_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/pmg-generator-windows-test.XXXXXX")
trap 'rm -rf "$TEST_ROOT"' EXIT

echo "==> Testing generate_standalone_windows.sh"

assert_no_shebang() {
  local count
  count=$(grep -c '^#!' "$1" || true)
  [[ "$count" -eq 0 ]] || fail "$1 must not contain a shebang"
}

line_number_of() {
  grep -Fnm1 "$2" "$1" | cut -d: -f1
}

OUT_ONE="${TEST_ROOT}/pmg-only"
OUT_TWO="${TEST_ROOT}/pmg-only-repeat"
"$GENERATOR" --output-dir "$OUT_ONE"
"$GENERATOR" --output-dir "$OUT_TWO"

INSTALL_ONE="${OUT_ONE}/${INSTALL_NAME}"
UNINSTALL_ONE="${OUT_ONE}/${UNINSTALL_NAME}"

for output in "$INSTALL_ONE" "$UNINSTALL_ONE"; do
  assert_file "$output"
  assert_no_shebang "$output"
  assert_equals "# Code generated by generate_standalone_windows.sh. Do not edit directly." \
    "$(head -n 1 "$output")" "first line of $output"
  # shellcheck disable=SC2016 # literal grep pattern, no expansion intended
  assert_not_contains "$output" '. "$PSScriptRoot\lib_windows.ps1"'
  assert_contains "$output" 'function Assert-Windows'
  assert_contains "$output" 'function Get-TargetUser'
  assert_contains "$output" 'function Invoke-AsUser'
  assert_contains "$output" 'Assert-Windows'
done
cmp "$INSTALL_ONE" "${OUT_TWO}/${INSTALL_NAME}"
cmp "$UNINSTALL_ONE" "${OUT_TWO}/${UNINSTALL_NAME}"

assert_contains "$INSTALL_ONE" 'function Install-Binary'
assert_contains "$INSTALL_ONE" 'function Set-UserCloud'
assert_contains "$UNINSTALL_ONE" 'function Remove-UserState'
assert_contains "$UNINSTALL_ONE" 'function Remove-Binary'

CRLF_ROOT="${TEST_ROOT}/crlf-source"
mkdir -p "$CRLF_ROOT/lib" "$CRLF_ROOT/windows"
cp "$GENERATOR" "$CRLF_ROOT/generate_standalone_windows.sh"
cp "${SCRIPT_DIR}/lib/generate_standalone_lib.sh" "$CRLF_ROOT/lib/generate_standalone_lib.sh"
for source in lib_windows.ps1 pmg_setup_install_windows.ps1 pmg_uninstall_windows.ps1; do
  awk '{ sub(/\r$/, ""); printf "%s\r\n", $0 }' "${SCRIPT_DIR}/windows/${source}" > "$CRLF_ROOT/windows/${source}"
done
CRLF_OUT="${TEST_ROOT}/crlf-output"
"$CRLF_ROOT/generate_standalone_windows.sh" --output-dir "$CRLF_OUT"
cmp "$INSTALL_ONE" "$CRLF_OUT/$INSTALL_NAME"
cmp "$UNINSTALL_ONE" "$CRLF_OUT/$UNINSTALL_NAME"

# The committed standalone scripts match the sources.
"$GENERATOR" --check

CONFIG="${TEST_ROOT}/config.yml"
cat > "$CONFIG" <<'YAML'
global_lockdown: true
cloud:
  enabled: true
YAML

# An embedded config is a PowerShell variable placed before the entry
# script reads it. The uninstaller never carries it.
CONFIG_OUT="${TEST_ROOT}/config-only"
"$GENERATOR" --config "$CONFIG" --output-dir "$CONFIG_OUT"
CONFIG_INSTALL="${CONFIG_OUT}/${INSTALL_NAME}"
CONFIG_UNINSTALL="${CONFIG_OUT}/${UNINSTALL_NAME}"
# shellcheck disable=SC2016 # literal grep pattern, no expansion intended
assert_contains "$CONFIG_INSTALL" "\$EMBEDDED_GLOBAL_CONFIG_B64='"
assert_not_contains "$CONFIG_UNINSTALL" "EMBEDDED_GLOBAL_CONFIG_B64='"
embedded_config=$(grep -Fm1 "EMBEDDED_GLOBAL_CONFIG_B64='" "$CONFIG_INSTALL" | cut -d"'" -f2 | decode_base64)
assert_equals "$(cat "$CONFIG")" "$embedded_config" "embedded config content"
embedded_line=$(line_number_of "$CONFIG_INSTALL" "EMBEDDED_GLOBAL_CONFIG_B64='")
# shellcheck disable=SC2016 # literal grep pattern, no expansion intended
read_line=$(line_number_of "$CONFIG_INSTALL" '$CloudApiKey = [string]$env:SAFEDEP_API_KEY')
[[ "$embedded_line" -lt "$read_line" ]] ||
  fail "the embedded config must precede the entry script (line $embedded_line vs $read_line)"

assert_fails "$GENERATOR" --config "${TEST_ROOT}/missing.yml" --output-dir "${TEST_ROOT}/missing-output"
: > "${TEST_ROOT}/empty.yml"
assert_fails "$GENERATOR" --config "${TEST_ROOT}/empty.yml" --output-dir "${TEST_ROOT}/empty-output"
assert_fails "$GENERATOR" --config "$CONFIG"

OVERSIZED_CONFIG="${TEST_ROOT}/oversized.yml"
awk 'BEGIN { printf "padding: "; for (i = 0; i < 160000; i++) printf "x"; printf "\n" }' > "$OVERSIZED_CONFIG"
OVERSIZED_STDERR="${TEST_ROOT}/oversized.stderr"
if "$GENERATOR" --config "$OVERSIZED_CONFIG" --output-dir "${TEST_ROOT}/oversized-output" >/dev/null 2>"$OVERSIZED_STDERR"; then
  fail "an installer larger than 200 KB must be refused"
fi
assert_contains "$OVERSIZED_STDERR" "must be smaller than 204800 bytes"
assert_absent "${TEST_ROOT}/oversized-output/${INSTALL_NAME}"

# Credentials never reach a child process of the generator, and never
# appear in clear text in an output or on a stream.
CHILD_PROBE_BIN="${TEST_ROOT}/child-probe-bin"
CHILD_ENV_LEAK_FILE="${TEST_ROOT}/child-env-leak"
mkdir -p "$CHILD_PROBE_BIN"
cat > "${CHILD_PROBE_BIN}/probe" <<'PROBE'
#!/bin/bash
if [[ -n "${SAFEDEP_API_KEY+x}" || -n "${SAFEDEP_TENANT_ID+x}" ]]; then
  printf '%s\n' "${0##*/}" >> "$CHILD_ENV_LEAK_FILE"
fi
real_command="/usr/bin/${0##*/}"
[[ -x "$real_command" ]] || real_command="/bin/${0##*/}"
[[ -x "$real_command" ]] || exit 1
exec "$real_command" "$@"
PROBE
for command in dirname grep base64 tr mkdir mktemp awk chmod wc mv rm cut head; do
  cp "${CHILD_PROBE_BIN}/probe" "${CHILD_PROBE_BIN}/${command}"
  chmod 0755 "${CHILD_PROBE_BIN}/${command}"
done

CREDENTIAL_OUT="${TEST_ROOT}/config-and-credentials"
GENERATOR_STDOUT="${TEST_ROOT}/credential.stdout"
GENERATOR_STDERR="${TEST_ROOT}/credential.stderr"
env PATH="${CHILD_PROBE_BIN}:${PATH}" CHILD_ENV_LEAK_FILE="$CHILD_ENV_LEAK_FILE" \
  SAFEDEP_API_KEY="$TEST_API_KEY" SAFEDEP_TENANT_ID="$TEST_TENANT_ID" \
  "$GENERATOR" --config "$CONFIG" --embed-cloud-credentials --output-dir "$CREDENTIAL_OUT" \
  >"$GENERATOR_STDOUT" 2>"$GENERATOR_STDERR"
[[ ! -e "$CHILD_ENV_LEAK_FILE" ]] ||
  fail "generator child inherited SAFEDEP credentials: $(tr '\n' ' ' < "$CHILD_ENV_LEAK_FILE")"
CREDENTIAL_INSTALL="${CREDENTIAL_OUT}/${INSTALL_NAME}"
CREDENTIAL_UNINSTALL="${CREDENTIAL_OUT}/${UNINSTALL_NAME}"
assert_contains "$GENERATOR_STDERR" "Warning: generated installer contains recoverable cloud credentials"
assert_not_contains "$GENERATOR_STDOUT" "$TEST_API_KEY"
assert_not_contains "$GENERATOR_STDERR" "$TEST_API_KEY"
embedded_api_key=$(grep -Fm1 "EMBEDDED_SAFEDEP_API_KEY_B64='" "$CREDENTIAL_INSTALL" | cut -d"'" -f2 | decode_base64)
embedded_tenant_id=$(grep -Fm1 "EMBEDDED_SAFEDEP_TENANT_ID_B64='" "$CREDENTIAL_INSTALL" | cut -d"'" -f2 | decode_base64)
assert_equals "$TEST_API_KEY" "$embedded_api_key" "embedded API key"
assert_equals "$TEST_TENANT_ID" "$embedded_tenant_id" "embedded tenant ID"

CREDENTIALS_ONLY_OUT="${TEST_ROOT}/credentials-only"
SAFEDEP_API_KEY="$TEST_API_KEY" SAFEDEP_TENANT_ID="$TEST_TENANT_ID" \
  "$GENERATOR" --embed-cloud-credentials --output-dir "$CREDENTIALS_ONLY_OUT" 2>/dev/null

assert_fails env -u SAFEDEP_API_KEY -u SAFEDEP_TENANT_ID \
  "$GENERATOR" --embed-cloud-credentials --output-dir "${TEST_ROOT}/missing-credentials-output"
assert_fails env SAFEDEP_API_KEY="$TEST_API_KEY" SAFEDEP_TENANT_ID="$TEST_TENANT_ID" \
  "$GENERATOR" --embed-cloud-credentials
assert_fails env SAFEDEP_API_KEY="$TEST_API_KEY" SAFEDEP_TENANT_ID="$TEST_TENANT_ID" \
  "$GENERATOR" --embed-cloud-credentials --check

assert_variant "pmg-only" "$INSTALL_ONE" "$UNINSTALL_ONE" "no" "no" "755"
assert_variant "config-only" "$CONFIG_INSTALL" "$CONFIG_UNINSTALL" "yes" "no" "755"
assert_variant "credentials-only" \
  "${CREDENTIALS_ONLY_OUT}/${INSTALL_NAME}" "${CREDENTIALS_ONLY_OUT}/${UNINSTALL_NAME}" "no" "yes" "700"
assert_variant "config-and-credentials" "$CREDENTIAL_INSTALL" "$CREDENTIAL_UNINSTALL" "yes" "yes" "700"

for generic_output in "${SCRIPT_DIR}/standalone/${INSTALL_NAME}" "${SCRIPT_DIR}/standalone/${UNINSTALL_NAME}"; do
  assert_not_contains "$generic_output" "EMBEDDED_GLOBAL_CONFIG_B64='"
  assert_not_contains "$generic_output" "EMBEDDED_SAFEDEP_API_KEY_B64='"
  assert_not_contains "$generic_output" "EMBEDDED_SAFEDEP_TENANT_ID_B64='"
done

# Every Windows script refuses a non-Windows host before it changes anything.
PWSH="${PWSH:-$(command -v pwsh || true)}"
if [[ -z "$PWSH" ]]; then
  echo "SKIP: the Windows guard check needs pwsh"
elif [[ "$(uname -s)" == MINGW* || "$(uname -s)" == MSYS* || "$(uname -s)" == CYGWIN* ]]; then
  echo "SKIP: the Windows guard check needs a non-Windows host"
else
  for script in \
    windows/pmg_setup_install_windows.ps1 \
    windows/pmg_uninstall_windows.ps1 \
    "standalone/${INSTALL_NAME}" \
    "standalone/${UNINSTALL_NAME}"; do
    if output=$("$PWSH" -NoProfile -File "${SCRIPT_DIR}/${script}" 2>&1); then
      fail "$script must refuse to run on $(uname -s)"
    fi
    [[ "$output" == *"this script is for Windows only"* ]] ||
      fail "$script did not print the Windows-only error: $output"
  done
fi

echo "PASS"
