#!/bin/bash
# generate_standalone_test.sh — test the standalone generators for every OS.
# Runs the same assertions against generate_standalone_macos.sh and
# generate_standalone_linux.sh.
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

# shellcheck source=test_lib.sh
source "${SCRIPT_DIR}/lib/test_lib.sh"

TEST_API_KEY="pmg-generator-test-api-key"
TEST_TENANT_ID="pmg-generator-test-tenant"

run_generator_tests() {
  local os="$1"
  local GENERATOR="${SCRIPT_DIR}/generate_standalone_${os}.sh"
  local TEST_ROOT
  TEST_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/pmg-generator-test.XXXXXX")
  trap 'rm -rf "$TEST_ROOT"' RETURN

  echo "==> Testing generate_standalone_${os}.sh"

  OUT_ONE="${TEST_ROOT}/pmg-only"
  OUT_TWO="${TEST_ROOT}/pmg-only-repeat"

  "$GENERATOR" --output-dir "$OUT_ONE"
  "$GENERATOR" --output-dir "$OUT_TWO"

  INSTALL_ONE="${OUT_ONE}/pmg_setup_install_${os}_standalone.sh"
  UNINSTALL_ONE="${OUT_ONE}/pmg_uninstall_${os}_standalone.sh"
  INSTALL_TWO="${OUT_TWO}/pmg_setup_install_${os}_standalone.sh"
  UNINSTALL_TWO="${OUT_TWO}/pmg_uninstall_${os}_standalone.sh"

  for output in "$INSTALL_ONE" "$UNINSTALL_ONE" "$INSTALL_TWO" "$UNINSTALL_TWO"; do
    assert_file "$output"
    assert_executable "$output"
    bash -n "$output"
    assert_one_shebang "$output"
    assert_not_contains "$output" "source \"\${SCRIPT_DIR}/lib_${os}.sh\""
    assert_contains "$output" "require_${os}()"
    assert_contains "$output" 'each_target_user()'
    assert_contains "$output" 'run_user_session()'
    assert_contains "$output" "# Code generated by generate_standalone_${os}.sh. Do not edit directly."
  done

  cmp "$INSTALL_ONE" "$INSTALL_TWO"
  cmp "$UNINSTALL_ONE" "$UNINSTALL_TWO"

  assert_contains "$INSTALL_ONE" 'install_via_release()'
  assert_contains "$INSTALL_ONE" 'configure_user()'
  assert_contains "$UNINSTALL_ONE" 'remove_user_state()'
  assert_contains "$UNINSTALL_ONE" 'remove_binary()'

  DIRECTORY_TARGET_OUT="${TEST_ROOT}/directory-target"
  mkdir -p "${DIRECTORY_TARGET_OUT}/pmg_setup_install_${os}_standalone.sh"
  assert_fails "$GENERATOR" --output-dir "$DIRECTORY_TARGET_OUT"

  SOURCE_OVERWRITE_FIXTURE="${TEST_ROOT}/source-overwrite"
  mkdir -p "$SOURCE_OVERWRITE_FIXTURE"
  mkdir -p "${SOURCE_OVERWRITE_FIXTURE}/lib" "${SOURCE_OVERWRITE_FIXTURE}/${os}"
  cp "$GENERATOR" \
    "$SOURCE_OVERWRITE_FIXTURE"
  cp "${SCRIPT_DIR}/lib/generate_standalone_lib.sh" \
    "${SOURCE_OVERWRITE_FIXTURE}/lib/"
  cp "${SCRIPT_DIR}/${os}/lib_${os}.sh" \
    "${SCRIPT_DIR}/${os}/pmg_setup_install_${os}.sh" \
    "${SCRIPT_DIR}/${os}/pmg_uninstall_${os}.sh" \
    "${SOURCE_OVERWRITE_FIXTURE}/${os}/"
  "${SOURCE_OVERWRITE_FIXTURE}/generate_standalone_${os}.sh" \
    --output-dir "$SOURCE_OVERWRITE_FIXTURE"
  cmp "${SCRIPT_DIR}/${os}/pmg_setup_install_${os}.sh" \
    "${SOURCE_OVERWRITE_FIXTURE}/${os}/pmg_setup_install_${os}.sh"
  cmp "${SCRIPT_DIR}/${os}/pmg_uninstall_${os}.sh" \
    "${SOURCE_OVERWRITE_FIXTURE}/${os}/pmg_uninstall_${os}.sh"
  assert_file "${SOURCE_OVERWRITE_FIXTURE}/pmg_setup_install_${os}_standalone.sh"
  assert_file "${SOURCE_OVERWRITE_FIXTURE}/pmg_uninstall_${os}_standalone.sh"

  CONFIG="${TEST_ROOT}/config.yml"
  cat > "$CONFIG" <<'EOF'
global_lockdown: true
cloud:
  enabled: true
EOF

  CONFIG_OUT="${TEST_ROOT}/config-only"
  "$GENERATOR" --config "$CONFIG" --output-dir "$CONFIG_OUT"

  CONFIG_INSTALL="${CONFIG_OUT}/pmg_setup_install_${os}_standalone.sh"
  CONFIG_UNINSTALL="${CONFIG_OUT}/pmg_uninstall_${os}_standalone.sh"

  assert_contains "$CONFIG_INSTALL" 'EMBEDDED_GLOBAL_CONFIG_B64='
  assert_not_contains "$CONFIG_UNINSTALL" 'EMBEDDED_GLOBAL_CONFIG_B64='
  # shellcheck disable=SC2016 # literal grep pattern, no expansion intended
  assert_not_contains "$GENERATOR" 'install_global_config "$embedded_config_tmp"'
  assert_equals "755" "$(file_mode "$CONFIG_INSTALL")" "config installer mode"
  assert_equals "755" "$(file_mode "$CONFIG_UNINSTALL")" "config uninstaller mode"

  embedded_line=$(grep -Fnm1 'EMBEDDED_GLOBAL_CONFIG_B64=' "$CONFIG_INSTALL" | cut -d: -f1)
  [[ -n "$embedded_line" ]] || fail "embedded config declaration missing"

  MARKER_FIXTURE="${TEST_ROOT}/marker-fixture"
  mkdir -p "$MARKER_FIXTURE"
  mkdir -p "${MARKER_FIXTURE}/lib" "${MARKER_FIXTURE}/${os}"
  cp "$GENERATOR" \
    "$MARKER_FIXTURE"
  cp "${SCRIPT_DIR}/lib/generate_standalone_lib.sh" \
    "${MARKER_FIXTURE}/lib/"
  cp "${SCRIPT_DIR}/${os}/lib_${os}.sh" \
    "${SCRIPT_DIR}/${os}/pmg_setup_install_${os}.sh" \
    "${SCRIPT_DIR}/${os}/pmg_uninstall_${os}.sh" \
    "${MARKER_FIXTURE}/${os}/"
  awk '
    NR > 1 && /^#/ && $0 != "# shellcheck source=lib_${os}.sh" {
      printf "# Fixture installer prose %d\n", NR
      next
    }
    { print }
  ' "${SCRIPT_DIR}/${os}/pmg_setup_install_${os}.sh" \
    > "${MARKER_FIXTURE}/${os}/pmg_setup_install_${os}.sh"
  if cmp -s \
    "${SCRIPT_DIR}/${os}/pmg_setup_install_${os}.sh" \
    "${MARKER_FIXTURE}/pmg_setup_install_${os}.sh"; then
    fail "marker-independence fixture did not change installer prose"
  fi
  "${MARKER_FIXTURE}/generate_standalone_${os}.sh" \
    --config "$CONFIG" \
    --output-dir "${MARKER_FIXTURE}/output"
  assert_contains \
    "${MARKER_FIXTURE}/output/pmg_setup_install_${os}_standalone.sh" \
    'EMBEDDED_GLOBAL_CONFIG_B64='

  assert_fails "$GENERATOR" \
    --config "${TEST_ROOT}/missing.yml" \
    --output-dir "${TEST_ROOT}/missing-output"

  EMPTY_CONFIG="${TEST_ROOT}/empty.yml"
  : > "$EMPTY_CONFIG"
  assert_fails "$GENERATOR" \
    --config "$EMPTY_CONFIG" \
    --output-dir "${TEST_ROOT}/empty-output"

  assert_fails "$GENERATOR" --config "$CONFIG"

  OVERSIZED_CONFIG="${TEST_ROOT}/oversized-intune-config.yml"
  OVERSIZED_STDERR="${TEST_ROOT}/oversized-intune.stderr"
  OVERSIZED_OUTPUT="${TEST_ROOT}/oversized-intune-output"
  awk 'BEGIN {
    printf "padding: "
    for (i = 0; i < 800000; i++) {
      printf "x"
    }
    printf "\n"
  }' > "$OVERSIZED_CONFIG"
  [[ "$(wc -c < "$OVERSIZED_CONFIG")" -lt 1048576 ]] ||
    fail "oversized installer fixture config must remain smaller than 1 MB"
  if "$GENERATOR" \
    --config "$OVERSIZED_CONFIG" \
    --output-dir "$OVERSIZED_OUTPUT" \
    >/dev/null 2>"$OVERSIZED_STDERR"; then
    fail "Intune must reject a generated installer larger than 1 MB"
  fi
  assert_contains "$OVERSIZED_STDERR" \
    "must be smaller than 1048576 bytes"
  assert_absent "${OVERSIZED_OUTPUT}/pmg_setup_install_${os}_standalone.sh"
  assert_absent "${OVERSIZED_OUTPUT}/pmg_uninstall_${os}_standalone.sh"

  OVERSIZED_EXISTING_OUTPUT="${TEST_ROOT}/oversized-intune-existing-output"
  mkdir -p "$OVERSIZED_EXISTING_OUTPUT"
  printf '%s\n' "existing installer" \
    > "${OVERSIZED_EXISTING_OUTPUT}/pmg_setup_install_${os}_standalone.sh"
  printf '%s\n' "existing uninstaller" \
    > "${OVERSIZED_EXISTING_OUTPUT}/pmg_uninstall_${os}_standalone.sh"
  assert_fails "$GENERATOR" \
    --config "$OVERSIZED_CONFIG" \
    --output-dir "$OVERSIZED_EXISTING_OUTPUT"
  assert_equals "existing installer" \
    "$(cat "${OVERSIZED_EXISTING_OUTPUT}/pmg_setup_install_${os}_standalone.sh")" \
    "oversized generation must not replace installer"
  assert_equals "existing uninstaller" \
    "$(cat "${OVERSIZED_EXISTING_OUTPUT}/pmg_uninstall_${os}_standalone.sh")" \
    "oversized generation must not replace uninstaller"

  CHILD_PROBE_BIN="${TEST_ROOT}/child-probe-bin"
  CHILD_ENV_LEAK_FILE="${TEST_ROOT}/child-env-leak"
  mkdir -p "$CHILD_PROBE_BIN"
  cat > "${CHILD_PROBE_BIN}/probe" <<'EOF'
#!/bin/bash
if [[ -n "${SAFEDEP_API_KEY+x}" || -n "${SAFEDEP_TENANT_ID+x}" ||
  -n "${CLOUD_API_KEY+x}" || -n "${CLOUD_TENANT_ID+x}" ]]; then
  printf '%s\n' "${0##*/}" >> "$CHILD_ENV_LEAK_FILE"
fi
real_command="/usr/bin/${0##*/}"
[[ -x "$real_command" ]] || real_command="/bin/${0##*/}"
[[ -x "$real_command" ]] || exit 1
exec "$real_command" "$@"
EOF
  for command in dirname grep base64 tr mkdir mktemp awk chmod bash wc mv rm; do
    cp "${CHILD_PROBE_BIN}/probe" "${CHILD_PROBE_BIN}/${command}"
    chmod 0755 "${CHILD_PROBE_BIN}/${command}"
  done

  CHILD_PROBE_OUT="${TEST_ROOT}/credentials-only"
  env \
    PATH="${CHILD_PROBE_BIN}:${PATH}" \
    CHILD_ENV_LEAK_FILE="$CHILD_ENV_LEAK_FILE" \
    SAFEDEP_API_KEY="$TEST_API_KEY" \
    SAFEDEP_TENANT_ID="$TEST_TENANT_ID" \
    "$GENERATOR" \
    --embed-cloud-credentials \
    --output-dir "$CHILD_PROBE_OUT" \
    >/dev/null
  [[ ! -e "$CHILD_ENV_LEAK_FILE" ]] ||
    fail "generator child inherited SAFEDEP credentials: $(tr '\n' ' ' < "$CHILD_ENV_LEAK_FILE")"

  AMBIENT_OUT="${TEST_ROOT}/ambient"
  SAFEDEP_API_KEY="$TEST_API_KEY" \
    SAFEDEP_TENANT_ID="$TEST_TENANT_ID" \
    "$GENERATOR" --output-dir "$AMBIENT_OUT"
  AMBIENT_INSTALL="${AMBIENT_OUT}/pmg_setup_install_${os}_standalone.sh"
  AMBIENT_UNINSTALL="${AMBIENT_OUT}/pmg_uninstall_${os}_standalone.sh"
  for output in "$AMBIENT_INSTALL" "$AMBIENT_UNINSTALL"; do
    assert_not_contains "$output" 'EMBEDDED_SAFEDEP_API_KEY_B64='
    assert_not_contains "$output" 'EMBEDDED_SAFEDEP_TENANT_ID_B64='
    assert_not_contains "$output" "$TEST_API_KEY"
    assert_not_contains "$output" "$TEST_TENANT_ID"
    assert_equals "755" "$(file_mode "$output")" "ambient output mode"
  done

  CREDENTIAL_OUT="${TEST_ROOT}/config-and-credentials"
  GENERATOR_STDOUT="${TEST_ROOT}/credential.stdout"
  GENERATOR_STDERR="${TEST_ROOT}/credential.stderr"
  SAFEDEP_API_KEY="$TEST_API_KEY" \
    SAFEDEP_TENANT_ID="$TEST_TENANT_ID" \
    "$GENERATOR" \
    --config "$CONFIG" \
    --embed-cloud-credentials \
    --output-dir "$CREDENTIAL_OUT" \
    >"$GENERATOR_STDOUT" 2>"$GENERATOR_STDERR"

  CREDENTIAL_INSTALL="${CREDENTIAL_OUT}/pmg_setup_install_${os}_standalone.sh"
  CREDENTIAL_UNINSTALL="${CREDENTIAL_OUT}/pmg_uninstall_${os}_standalone.sh"

  assert_contains "$CREDENTIAL_INSTALL" 'EMBEDDED_SAFEDEP_API_KEY_B64='
  assert_contains "$CREDENTIAL_INSTALL" 'EMBEDDED_SAFEDEP_TENANT_ID_B64='
  assert_not_contains "$CREDENTIAL_INSTALL" "$TEST_API_KEY"
  assert_not_contains "$CREDENTIAL_INSTALL" "$TEST_TENANT_ID"
  assert_not_contains "$CREDENTIAL_UNINSTALL" 'EMBEDDED_SAFEDEP_API_KEY_B64='
  assert_not_contains "$CREDENTIAL_UNINSTALL" 'EMBEDDED_SAFEDEP_TENANT_ID_B64='
  assert_not_contains "$CREDENTIAL_UNINSTALL" "$TEST_API_KEY"
  assert_not_contains "$CREDENTIAL_UNINSTALL" "$TEST_TENANT_ID"
  assert_equals "700" "$(file_mode "$CREDENTIAL_INSTALL")" \
    "credential installer mode"
  assert_equals "755" "$(file_mode "$CREDENTIAL_UNINSTALL")" \
    "credential uninstaller mode"
  assert_contains "$GENERATOR_STDERR" \
    "Warning: generated installer contains recoverable cloud credentials"
  assert_not_contains "$GENERATOR_STDOUT" "$TEST_API_KEY"
  assert_not_contains "$GENERATOR_STDOUT" "$TEST_TENANT_ID"
  assert_not_contains "$GENERATOR_STDERR" "$TEST_API_KEY"
  assert_not_contains "$GENERATOR_STDERR" "$TEST_TENANT_ID"

  embedded_api_key=$(
    grep -Fm1 'EMBEDDED_SAFEDEP_API_KEY_B64=' "$CREDENTIAL_INSTALL" |
      cut -d"'" -f2 |
      decode_base64
  )
  embedded_tenant_id=$(
    grep -Fm1 'EMBEDDED_SAFEDEP_TENANT_ID_B64=' "$CREDENTIAL_INSTALL" |
      cut -d"'" -f2 |
      decode_base64
  )
  assert_equals "$TEST_API_KEY" "$embedded_api_key" "embedded API key"
  assert_equals "$TEST_TENANT_ID" "$embedded_tenant_id" "embedded tenant ID"
  assert_not_contains "$CREDENTIAL_UNINSTALL" \
    "$(printf '%s' "$TEST_API_KEY" | encode_base64)"
  assert_not_contains "$CREDENTIAL_UNINSTALL" \
    "$(printf '%s' "$TEST_TENANT_ID" | encode_base64)"

  FAILED_UNINSTALL_OUT="${TEST_ROOT}/failed-uninstaller"
  mkdir -p \
    "${FAILED_UNINSTALL_OUT}/pmg_uninstall_${os}_standalone.sh"
  printf '%s\n' "existing installer" \
    > "${FAILED_UNINSTALL_OUT}/pmg_setup_install_${os}_standalone.sh"
  assert_fails env SAFEDEP_API_KEY="$TEST_API_KEY" \
    SAFEDEP_TENANT_ID="$TEST_TENANT_ID" \
    "$GENERATOR" \
    --embed-cloud-credentials \
    --output-dir "$FAILED_UNINSTALL_OUT"
  assert_equals "existing installer" \
    "$(cat "${FAILED_UNINSTALL_OUT}/pmg_setup_install_${os}_standalone.sh")" \
    "failed uninstaller generation must not rewrite installer"

  FAILED_INSTALL_OUT="${TEST_ROOT}/failed-installer"
  mkdir -p "${FAILED_INSTALL_OUT}/pmg_setup_install_${os}_standalone.sh"
  printf '%s\n' "existing uninstaller" \
    > "${FAILED_INSTALL_OUT}/pmg_uninstall_${os}_standalone.sh"
  assert_fails env SAFEDEP_API_KEY="$TEST_API_KEY" \
    SAFEDEP_TENANT_ID="$TEST_TENANT_ID" \
    "$GENERATOR" \
    --embed-cloud-credentials \
    --output-dir "$FAILED_INSTALL_OUT"
  assert_equals "existing uninstaller" \
    "$(cat "${FAILED_INSTALL_OUT}/pmg_uninstall_${os}_standalone.sh")" \
    "failed installer generation must not rewrite uninstaller"

  assert_fails env -u SAFEDEP_API_KEY -u SAFEDEP_TENANT_ID \
    "$GENERATOR" \
    --embed-cloud-credentials \
    --output-dir "${TEST_ROOT}/missing-credentials-output"

  assert_fails env -u SAFEDEP_TENANT_ID SAFEDEP_API_KEY="$TEST_API_KEY" \
    "$GENERATOR" \
    --embed-cloud-credentials \
    --output-dir "${TEST_ROOT}/api-key-only-output"

  assert_fails env -u SAFEDEP_API_KEY SAFEDEP_TENANT_ID="$TEST_TENANT_ID" \
    "$GENERATOR" \
    --embed-cloud-credentials \
    --output-dir "${TEST_ROOT}/tenant-only-output"

  assert_fails env SAFEDEP_API_KEY="" SAFEDEP_TENANT_ID="$TEST_TENANT_ID" \
    "$GENERATOR" \
    --embed-cloud-credentials \
    --output-dir "${TEST_ROOT}/empty-api-key-output"

  assert_fails env SAFEDEP_API_KEY="$TEST_API_KEY" SAFEDEP_TENANT_ID="" \
    "$GENERATOR" \
    --embed-cloud-credentials \
    --output-dir "${TEST_ROOT}/empty-tenant-output"

  assert_fails env SAFEDEP_API_KEY="$TEST_API_KEY" \
    SAFEDEP_TENANT_ID="$TEST_TENANT_ID" \
    "$GENERATOR" --embed-cloud-credentials

  assert_fails env SAFEDEP_API_KEY="$TEST_API_KEY" \
    SAFEDEP_TENANT_ID="$TEST_TENANT_ID" \
    "$GENERATOR" --embed-cloud-credentials --check

  assert_fails "$GENERATOR" \
    --cloud-credentials "${TEST_ROOT}/credentials.env" \
    --output-dir "${TEST_ROOT}/removed-credential-flag-output"

  CLI_SECRET_STDOUT="${TEST_ROOT}/cli-secret.stdout"
  CLI_SECRET_STDERR="${TEST_ROOT}/cli-secret.stderr"
  if env SAFEDEP_API_KEY="$TEST_API_KEY" SAFEDEP_TENANT_ID="$TEST_TENANT_ID" \
    "$GENERATOR" \
    --embed-cloud-credentials \
    "$TEST_API_KEY" \
    --output-dir "${TEST_ROOT}/cli-secret-output" \
    >"$CLI_SECRET_STDOUT" 2>"$CLI_SECRET_STDERR"; then
    fail "credential flag must not accept an API key argument"
  fi
  assert_not_contains "$CLI_SECRET_STDOUT" "$TEST_API_KEY"
  assert_not_contains "$CLI_SECRET_STDERR" "$TEST_API_KEY"

  assert_variant "pmg-only" \
    "$INSTALL_ONE" "$UNINSTALL_ONE" "no" "no" "755"
  assert_variant "config-only" \
    "$CONFIG_INSTALL" "$CONFIG_UNINSTALL" "yes" "no" "755"
  assert_variant "credentials-only" \
    "${CHILD_PROBE_OUT}/pmg_setup_install_${os}_standalone.sh" \
    "${CHILD_PROBE_OUT}/pmg_uninstall_${os}_standalone.sh" \
    "no" "yes" "700"
  assert_variant "config-and-credentials" \
    "$CREDENTIAL_INSTALL" "$CREDENTIAL_UNINSTALL" "yes" "yes" "700"

  for generic_output in \
    "${SCRIPT_DIR}/standalone/pmg_setup_install_${os}_standalone.sh" \
    "${SCRIPT_DIR}/standalone/pmg_uninstall_${os}_standalone.sh"; do
    assert_not_contains "$generic_output" "EMBEDDED_GLOBAL_CONFIG_B64='"
    assert_not_contains "$generic_output" "EMBEDDED_SAFEDEP_API_KEY_B64='"
    assert_not_contains "$generic_output" "EMBEDDED_SAFEDEP_TENANT_ID_B64='"
    assert_not_contains "$generic_output" "$TEST_API_KEY"
    assert_not_contains "$generic_output" "$TEST_TENANT_ID"
  done
}

for os in macos linux; do
  run_generator_tests "$os"
done

echo "PASS"
