name: Issue Triage

on:
  issues:
    types: [opened]

# The workflow does not use the default token.
# Project access is handled by ISSUE_TRIAGE_GITHUB_TOKEN secret.
permissions: {}

jobs:
  triage:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Add to SafeDep Operations project
        uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
        with:
          project-url: https://github.com/orgs/safedep/projects/5
          github-token: ${{ secrets.ISSUE_TRIAGE_GITHUB_TOKEN }}
